
-- =============================================
-- Author:		Jessica Gutierrez
-- Description:	Add Tool Online Rules
-- =============================================
CREATE Procedure [dbo].[AddToolOnlineRules]
@Corporative varchar(50),
 @ToolOnline varchar(30),
 @Attribute1 varchar(50),
 @Supervisor varchar(50),
 @SupAgent int,
 @SupPCC varchar(50),
 @SupStatus char(20),
 @Consultor1 varchar(50),
 @ConAgent1 int,
 @ConPCC1 varchar(50),
 @ConStatus1 char(20),
 @Consultor2 varchar(50),
 @ConAgent2 int,
 @ConPCC2 varchar(50),
 @ConStatus2 char(20),
 @Consultor3 varchar(50),
 @ConAgent3 int,
 @ConPCC3 varchar(50),
 @ConStatus3 char(20),
 @Consultor4 varchar(50),
 @ConAgent4 int,
 @ConPCC4 varchar(50),
 @ConStatus4 char(20),
 @Consultor5 varchar(50),
 @ConAgent5 int,
 @ConPCC5 varchar(50),
 @ConStatus5 char(20),
 @FechaInsert datetime,
 @InsertBy int,
 @FechaUpdate datetime,
 @UpdateBy int

 
AS
INSERT INTO [dbo].[ToolOnlineRules]
           ( Corporative,
             ToolOnline ,          
             Attribute1,
             Supervisor,
		     SupAgent,
 			 SupPCC,
			 SupStatus,
			 Consultor1, 
			 ConAgent1,
			 ConPCC1,
			 ConStatus1, 
			 CountConsul1,
			 Consultor2, 
			 ConAgent2,
			 ConPCC2, 
			 ConStatus2,
			 CountConsul2, 
			 Consultor3, 
			 ConAgent3,
			 ConPCC3,
			 ConStatus3,
			 CountConsul3,
			 Consultor4, 
			 ConAgent4,
			 ConPCC4, 
			 ConStatus4, 
			 CountConsul4,
			 Consultor5, 
			 ConAgent5,
			 ConPCC5, 
			 ConStatus5, 
			 CountConsul5,
			 FechaInsert, 
			 InsertBy,
			 FechaUpdate,
			 UpdateBy 
           )
     VALUES
           (
			 @Corporative,
			 @ToolOnline,
			 @Attribute1,
			 @Supervisor,
			 @SupAgent,
			 @SupPCC,
			 @SupStatus,
			 @Consultor1, 
			 @ConAgent1,
			 @ConPCC1, 
			 @ConStatus1, 
			 0,
			 @Consultor2, 
			 @ConAgent2,
			 @ConPCC2, 
			 @ConStatus2,
			 0, 
			 @Consultor3, 
			 @ConAgent3,
			 @ConPCC3,
			 @ConStatus3,
			 0,
			 @Consultor4, 
			 @ConAgent4,
			 @ConPCC4, 
			 @ConStatus4, 
			 0,
			 @Consultor5, 
			 @ConAgent5, 
			 @ConPCC5,
			 @ConStatus5,
			 0,
			 @FechaInsert, 
			 @InsertBy,
			 @FechaUpdate,
			 @UpdateBy 
          )