//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace MyCTS.Services.MyCTSOracleConnection {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetProfileByLocationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAttributeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLocationByAttribute1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoByTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCreditCardNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegenerateInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTranferCheckNumberOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::MyCTS.Services.Properties.Settings.Default.MyCTS_Services_MyCTSOracleConnection_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProfileByLocationCompletedEventHandler GetProfileByLocationCompleted;
        
        /// <remarks/>
        public event GetAttributeCompletedEventHandler GetAttributeCompleted;
        
        /// <remarks/>
        public event GetLocationByAttribute1CompletedEventHandler GetLocationByAttribute1Completed;
        
        /// <remarks/>
        public event GetInfoByTicketCompletedEventHandler GetInfoByTicketCompleted;
        
        /// <remarks/>
        public event GetCreditCardNumberCompletedEventHandler GetCreditCardNumberCompleted;
        
        /// <remarks/>
        public event RegenerateInvoiceCompletedEventHandler RegenerateInvoiceCompleted;
        
        /// <remarks/>
        public event GetTranferCheckNumberCompletedEventHandler GetTranferCheckNumberCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProfileByLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cat1stStarInfoByLocation GetProfileByLocation(string location, int orgId) {
            object[] results = this.Invoke("GetProfileByLocation", new object[] {
                        location,
                        orgId});
            return ((Cat1stStarInfoByLocation)(results[0]));
        }
        
        /// <remarks/>
        public void GetProfileByLocationAsync(string location, int orgId) {
            this.GetProfileByLocationAsync(location, orgId, null);
        }
        
        /// <remarks/>
        public void GetProfileByLocationAsync(string location, int orgId, object userState) {
            if ((this.GetProfileByLocationOperationCompleted == null)) {
                this.GetProfileByLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfileByLocationOperationCompleted);
            }
            this.InvokeAsync("GetProfileByLocation", new object[] {
                        location,
                        orgId}, this.GetProfileByLocationOperationCompleted, userState);
        }
        
        private void OnGetProfileByLocationOperationCompleted(object arg) {
            if ((this.GetProfileByLocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProfileByLocationCompleted(this, new GetProfileByLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAttribute", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetAttribute1 GetAttribute(string location, int orgId) {
            object[] results = this.Invoke("GetAttribute", new object[] {
                        location,
                        orgId});
            return ((GetAttribute1)(results[0]));
        }
        
        /// <remarks/>
        public void GetAttributeAsync(string location, int orgId) {
            this.GetAttributeAsync(location, orgId, null);
        }
        
        /// <remarks/>
        public void GetAttributeAsync(string location, int orgId, object userState) {
            if ((this.GetAttributeOperationCompleted == null)) {
                this.GetAttributeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAttributeOperationCompleted);
            }
            this.InvokeAsync("GetAttribute", new object[] {
                        location,
                        orgId}, this.GetAttributeOperationCompleted, userState);
        }
        
        private void OnGetAttributeOperationCompleted(object arg) {
            if ((this.GetAttributeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAttributeCompleted(this, new GetAttributeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLocationByAttribute1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetLocationByAttribute1(string attribute1, int orgId) {
            object[] results = this.Invoke("GetLocationByAttribute1", new object[] {
                        attribute1,
                        orgId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLocationByAttribute1Async(string attribute1, int orgId) {
            this.GetLocationByAttribute1Async(attribute1, orgId, null);
        }
        
        /// <remarks/>
        public void GetLocationByAttribute1Async(string attribute1, int orgId, object userState) {
            if ((this.GetLocationByAttribute1OperationCompleted == null)) {
                this.GetLocationByAttribute1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLocationByAttribute1OperationCompleted);
            }
            this.InvokeAsync("GetLocationByAttribute1", new object[] {
                        attribute1,
                        orgId}, this.GetLocationByAttribute1OperationCompleted, userState);
        }
        
        private void OnGetLocationByAttribute1OperationCompleted(object arg) {
            if ((this.GetLocationByAttribute1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLocationByAttribute1Completed(this, new GetLocationByAttribute1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfoByTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetInfoByTicket(string ticket, int orgId) {
            object[] results = this.Invoke("GetInfoByTicket", new object[] {
                        ticket,
                        orgId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoByTicketAsync(string ticket, int orgId) {
            this.GetInfoByTicketAsync(ticket, orgId, null);
        }
        
        /// <remarks/>
        public void GetInfoByTicketAsync(string ticket, int orgId, object userState) {
            if ((this.GetInfoByTicketOperationCompleted == null)) {
                this.GetInfoByTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoByTicketOperationCompleted);
            }
            this.InvokeAsync("GetInfoByTicket", new object[] {
                        ticket,
                        orgId}, this.GetInfoByTicketOperationCompleted, userState);
        }
        
        private void OnGetInfoByTicketOperationCompleted(object arg) {
            if ((this.GetInfoByTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoByTicketCompleted(this, new GetInfoByTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCreditCardNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCreditCardNumber(string dk, string cardType, int orgId) {
            object[] results = this.Invoke("GetCreditCardNumber", new object[] {
                        dk,
                        cardType,
                        orgId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCreditCardNumberAsync(string dk, string cardType, int orgId) {
            this.GetCreditCardNumberAsync(dk, cardType, orgId, null);
        }
        
        /// <remarks/>
        public void GetCreditCardNumberAsync(string dk, string cardType, int orgId, object userState) {
            if ((this.GetCreditCardNumberOperationCompleted == null)) {
                this.GetCreditCardNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCreditCardNumberOperationCompleted);
            }
            this.InvokeAsync("GetCreditCardNumber", new object[] {
                        dk,
                        cardType,
                        orgId}, this.GetCreditCardNumberOperationCompleted, userState);
        }
        
        private void OnGetCreditCardNumberOperationCompleted(object arg) {
            if ((this.GetCreditCardNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCreditCardNumberCompleted(this, new GetCreditCardNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegenerateInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegenerateInvoice(string typeInvoice, string numberDocument, int orgId) {
            object[] results = this.Invoke("RegenerateInvoice", new object[] {
                        typeInvoice,
                        numberDocument,
                        orgId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegenerateInvoiceAsync(string typeInvoice, string numberDocument, int orgId) {
            this.RegenerateInvoiceAsync(typeInvoice, numberDocument, orgId, null);
        }
        
        /// <remarks/>
        public void RegenerateInvoiceAsync(string typeInvoice, string numberDocument, int orgId, object userState) {
            if ((this.RegenerateInvoiceOperationCompleted == null)) {
                this.RegenerateInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegenerateInvoiceOperationCompleted);
            }
            this.InvokeAsync("RegenerateInvoice", new object[] {
                        typeInvoice,
                        numberDocument,
                        orgId}, this.RegenerateInvoiceOperationCompleted, userState);
        }
        
        private void OnRegenerateInvoiceOperationCompleted(object arg) {
            if ((this.RegenerateInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegenerateInvoiceCompleted(this, new RegenerateInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTranferCheckNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTranferCheckNumber(string dk) {
            object[] results = this.Invoke("GetTranferCheckNumber", new object[] {
                        dk});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTranferCheckNumberAsync(string dk) {
            this.GetTranferCheckNumberAsync(dk, null);
        }
        
        /// <remarks/>
        public void GetTranferCheckNumberAsync(string dk, object userState) {
            if ((this.GetTranferCheckNumberOperationCompleted == null)) {
                this.GetTranferCheckNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTranferCheckNumberOperationCompleted);
            }
            this.InvokeAsync("GetTranferCheckNumber", new object[] {
                        dk}, this.GetTranferCheckNumberOperationCompleted, userState);
        }
        
        private void OnGetTranferCheckNumberOperationCompleted(object arg) {
            if ((this.GetTranferCheckNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTranferCheckNumberCompleted(this, new GetTranferCheckNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cat1stStarInfoByLocation {
        
        private string locationField;
        
        private string attribute1Field;
        
        private string customerNameField;
        
        private string addressField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string address4Field;
        
        private string cityField;
        
        private string municipalityField;
        
        private string postalCodeField;
        
        private string stateField;
        
        private string rFCField;
        
        private string mainPhoneField;
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Attribute1 {
            get {
                return this.attribute1Field;
            }
            set {
                this.attribute1Field = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string Address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
            }
        }
        
        /// <remarks/>
        public string Address4 {
            get {
                return this.address4Field;
            }
            set {
                this.address4Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
            }
        }
        
        /// <remarks/>
        public string MainPhone {
            get {
                return this.mainPhoneField;
            }
            set {
                this.mainPhoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAttribute1 {
        
        private string locationField;
        
        private string attribute1Field;
        
        private string statusField;
        
        private string status_SiteField;
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Attribute1 {
            get {
                return this.attribute1Field;
            }
            set {
                this.attribute1Field = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Status_Site {
            get {
                return this.status_SiteField;
            }
            set {
                this.status_SiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProfileByLocationCompletedEventHandler(object sender, GetProfileByLocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProfileByLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProfileByLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cat1stStarInfoByLocation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cat1stStarInfoByLocation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAttributeCompletedEventHandler(object sender, GetAttributeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAttributeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAttributeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAttribute1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAttribute1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetLocationByAttribute1CompletedEventHandler(object sender, GetLocationByAttribute1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLocationByAttribute1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLocationByAttribute1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetInfoByTicketCompletedEventHandler(object sender, GetInfoByTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoByTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoByTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCreditCardNumberCompletedEventHandler(object sender, GetCreditCardNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCreditCardNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCreditCardNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void RegenerateInvoiceCompletedEventHandler(object sender, RegenerateInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegenerateInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegenerateInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetTranferCheckNumberCompletedEventHandler(object sender, GetTranferCheckNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTranferCheckNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTranferCheckNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591