//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.Presentation.Resources.Group {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.Presentation.Resources.Group.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0A.
        /// </summary>
        internal static string COMMANDS_0A {
            get {
                return ResourceManager.GetString("COMMANDS_0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5H-&lt;/CG*{0}/&gt;.
        /// </summary>
        internal static string COMMANDS_5H_ENDIT_CG_AST {
            get {
                return ResourceManager.GetString("COMMANDS_5H_ENDIT_CG_AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7TAW.
        /// </summary>
        internal static string COMMANDS_7TAW {
            get {
                return ResourceManager.GetString("COMMANDS_7TAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string COMMANDS_AST {
            get {
                return ResourceManager.GetString("COMMANDS_AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *A.
        /// </summary>
        internal static string COMMANDS_AST_A {
            get {
                return ResourceManager.GetString("COMMANDS_AST_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *-B/.
        /// </summary>
        internal static string COMMANDS_AST_INDENT_B_SLASH {
            get {
                return ResourceManager.GetString("COMMANDS_AST_INDENT_B_SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *PAD.
        /// </summary>
        internal static string COMMANDS_AST_PAD {
            get {
                return ResourceManager.GetString("COMMANDS_AST_PAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK.
        /// </summary>
        internal static string COMMANDS_DK {
            get {
                return ResourceManager.GetString("COMMANDS_DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string COMMANDS_EIGHT {
            get {
                return ResourceManager.GetString("COMMANDS_EIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -B/.
        /// </summary>
        internal static string COMMANDS_INDENT_B_SLASH {
            get {
                return ResourceManager.GetString("COMMANDS_INDENT_B_SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NN.
        /// </summary>
        internal static string COMMANDS_NN {
            get {
                return ResourceManager.GetString("COMMANDS_NN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string COMMANDS_ZERO {
            get {
                return ResourceManager.GetString("COMMANDS_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0*.
        /// </summary>
        internal static string COMMANDS_ZERO_AST {
            get {
                return ResourceManager.GetString("COMMANDS_ZERO_AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string INDENT {
            get {
                return ResourceManager.GetString("INDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string SLASH {
            get {
                return ResourceManager.GetString("SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucDefineGroup.
        /// </summary>
        internal static string UC_DEFINEGROUP {
            get {
                return ResourceManager.GetString("UC_DEFINEGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucInsertDataPassenger.
        /// </summary>
        internal static string UC_INSERTDATAPASSENGER {
            get {
                return ResourceManager.GetString("UC_INSERTDATAPASSENGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucInsertDataPassenger2.
        /// </summary>
        internal static string UC_INSERTDATAPASSENGER2 {
            get {
                return ResourceManager.GetString("UC_INSERTDATAPASSENGER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucManualRateGroup.
        /// </summary>
        internal static string UC_MANUALRATEGROUP {
            get {
                return ResourceManager.GetString("UC_MANUALRATEGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucRecoverGroup.
        /// </summary>
        internal static string UC_RECOVERGROUP {
            get {
                return ResourceManager.GetString("UC_RECOVERGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucSellSegmentGK.
        /// </summary>
        internal static string UC_SELLSEGMENTGK {
            get {
                return ResourceManager.GetString("UC_SELLSEGMENTGK", resourceCulture);
            }
        }
    }
}
