//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.Presentation.Resources.Group {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Group {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Group() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.Presentation.Resources.Group.Group", typeof(Group).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR AL VENDER VUELO, REINTENTA.
        /// </summary>
        internal static string ERROR_VENDER_VUELO {
            get {
                return ResourceManager.GetString("ERROR_VENDER_VUELO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE AEROLINEA.
        /// </summary>
        internal static string REQUIERE_INGRESE_AEROLINEA {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_AEROLINEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE AEROLINEA VALIDA.
        /// </summary>
        internal static string REQUIERE_INGRESE_AEROLINEA_VALIDA {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_AEROLINEA_VALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE CAMPOS OBLIGATORIOS.
        /// </summary>
        internal static string REQUIERE_INGRESE_CAMPOS_OBLIGATORIOS {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_CAMPOS_OBLIGATORIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE CIUDAD VALIDA.
        /// </summary>
        internal static string REQUIERE_INGRESE_CIUDAD_VALIDA {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_CIUDAD_VALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE DK.
        /// </summary>
        internal static string REQUIERE_INGRESE_DK {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE DK VALIDO.
        /// </summary>
        internal static string REQUIERE_INGRESE_DK_VALIDO {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_DK_VALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE ESPACIOS A RESEVAR.
        /// </summary>
        internal static string REQUIERE_INGRESE_ESPACIOS_RESERVAR {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_ESPACIOS_RESERVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE FECHA.
        /// </summary>
        internal static string REQUIERE_INGRESE_FECHA {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_FECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE HORA DE SALIDA.
        /// </summary>
        internal static string REQUIERE_INGRESE_HORA_SALIDA {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_HORA_SALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE LUGAR DE RESERVACIÓN.
        /// </summary>
        internal static string REQUIERE_INGRESE_LUGAR_RESERVACION {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_LUGAR_RESERVACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE LUGARES A RESERVAR.
        /// </summary>
        internal static string REQUIERE_INGRESE_LUGARESRESERVAR {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_LUGARESRESERVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE NOMBRE DEL GRUPO.
        /// </summary>
        internal static string REQUIERE_INGRESE_NOMBRE_GRUPO {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_NOMBRE_GRUPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE ORIGEN DE CIUDAD.
        /// </summary>
        internal static string REQUIERE_INGRESE_ORIGEN_CIUDAD {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_ORIGEN_CIUDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE RECORD LOCALIZADOR.
        /// </summary>
        internal static string REQUIERE_INGRESE_RECORDLOCALIZADOR {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_RECORDLOCALIZADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE TIEMPO LIMITE.
        /// </summary>
        internal static string REQUIERE_INGRESE_TIEMPOLIMITE {
            get {
                return ResourceManager.GetString("REQUIERE_INGRESE_TIEMPOLIMITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUIERE SE INGRESE CODIGO DE GRUPO.
        /// </summary>
        internal static string REQUIERES_INGRESE_CODIGO_GRUPO {
            get {
                return ResourceManager.GetString("REQUIERES_INGRESE_CODIGO_GRUPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAVOR DE VERIFICAR QUE ESTEN LOS DATOS COMPLETOS EN LA FILA.
        /// </summary>
        internal static string VERIFIQUE_RENGLONES {
            get {
                return ResourceManager.GetString("VERIFIQUE_RENGLONES", resourceCulture);
            }
        }
    }
}
