//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BodyMailCancelTicketResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BodyMailCancelTicketResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.Presentation.Resources.BodyMailCancelTicketResources", typeof(BodyMailCancelTicketResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;border-collapse: collapse&quot; &gt;
        ///    &lt;tr&gt;
        ///        &lt;td colspan=&quot;10&quot;&gt;
        ///            &lt;span style=&quot;font-size: 11pt; font-family: Arial&quot;&gt;Estimado &lt;strong&gt;[*usuario*]&lt;/strong&gt;&lt;/span&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr style=&quot;font-size: 12pt; font-family: Times New Roman&quot;&gt;
        ///        &lt;td colspan=&quot;10&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr style=&quot;font-size: 12pt; font-family: Times New Roman&quot;&gt;
        ///        &lt;td colspan=&quot;10&quot;&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr style=&quot;font-size: 12pt; font-family: Times New Roman&quot;&gt;
        ///        &lt;td colspan=&quot;10&quot;&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BODY {
            get {
                return ResourceManager.GetString("BODY", resourceCulture);
            }
        }
    }
}
