//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.Presentation.Resources.Queues {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.Presentation.Resources.Queues.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string AST {
            get {
                return ResourceManager.GetString("AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Q.
        /// </summary>
        internal static string COMMANDS_AST_Q {
            get {
                return ResourceManager.GetString("COMMANDS_AST_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‡NM-.
        /// </summary>
        internal static string COMMANDS_CROSSLORAINE_NM_INDENT {
            get {
                return ResourceManager.GetString("COMMANDS_CROSSLORAINE_NM_INDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string COMMANDS_E {
            get {
                return ResourceManager.GetString("COMMANDS_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EWL.
        /// </summary>
        internal static string COMMANDS_EWL {
            get {
                return ResourceManager.GetString("COMMANDS_EWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        internal static string COMMANDS_H {
            get {
                return ResourceManager.GetString("COMMANDS_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H/A.
        /// </summary>
        internal static string COMMANDS_H_SLASH_A {
            get {
                return ResourceManager.GetString("COMMANDS_H_SLASH_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H/A,S.
        /// </summary>
        internal static string COMMANDS_H_SLASH_A_COMMA_S {
            get {
                return ResourceManager.GetString("COMMANDS_H_SLASH_A_COMMA_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H/S.
        /// </summary>
        internal static string COMMANDS_H_SLASH_S {
            get {
                return ResourceManager.GetString("COMMANDS_H_SLASH_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string COMMANDS_I {
            get {
                return ResourceManager.GetString("COMMANDS_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        internal static string COMMANDS_Q {
            get {
                return ResourceManager.GetString("COMMANDS_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q*.
        /// </summary>
        internal static string COMMANDS_Q_AST {
            get {
                return ResourceManager.GetString("COMMANDS_Q_AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q/.
        /// </summary>
        internal static string COMMANDS_Q_SLAHS {
            get {
                return ResourceManager.GetString("COMMANDS_Q_SLAHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q/.
        /// </summary>
        internal static string COMMANDS_Q_SLASH {
            get {
                return ResourceManager.GetString("COMMANDS_Q_SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QBE.
        /// </summary>
        internal static string COMMANDS_QBE {
            get {
                return ResourceManager.GetString("COMMANDS_QBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QBI.
        /// </summary>
        internal static string COMMANDS_QBI {
            get {
                return ResourceManager.GetString("COMMANDS_QBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QBR.
        /// </summary>
        internal static string COMMANDS_QBR {
            get {
                return ResourceManager.GetString("COMMANDS_QBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC/.
        /// </summary>
        internal static string COMMANDS_QC_SLASH {
            get {
                return ResourceManager.GetString("COMMANDS_QC_SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QH.
        /// </summary>
        internal static string COMMANDS_QH {
            get {
                return ResourceManager.GetString("COMMANDS_QH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QI*.
        /// </summary>
        internal static string COMMANDS_QI_AST {
            get {
                return ResourceManager.GetString("COMMANDS_QI_AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QI*S*.
        /// </summary>
        internal static string COMMANDS_QI_AST_S_AST {
            get {
                return ResourceManager.GetString("COMMANDS_QI_AST_S_AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QI/.
        /// </summary>
        internal static string COMMANDS_QI_SLASH {
            get {
                return ResourceManager.GetString("COMMANDS_QI_SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QMOV/.
        /// </summary>
        internal static string COMMANDS_QMOV_SLASH {
            get {
                return ResourceManager.GetString("COMMANDS_QMOV_SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QP/.
        /// </summary>
        internal static string COMMANDS_QP_SLASH {
            get {
                return ResourceManager.GetString("COMMANDS_QP_SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR.
        /// </summary>
        internal static string COMMANDS_QR {
            get {
                return ResourceManager.GetString("COMMANDS_QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QXE.
        /// </summary>
        internal static string COMMANDS_QXE {
            get {
                return ResourceManager.GetString("COMMANDS_QXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QXER.
        /// </summary>
        internal static string COMMANDS_QXER {
            get {
                return ResourceManager.GetString("COMMANDS_QXER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QXI.
        /// </summary>
        internal static string COMMANDS_QXI {
            get {
                return ResourceManager.GetString("COMMANDS_QXI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QXIR.
        /// </summary>
        internal static string COMMANDS_QXIR {
            get {
                return ResourceManager.GetString("COMMANDS_QXIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QXR.
        /// </summary>
        internal static string COMMANDS_QXR {
            get {
                return ResourceManager.GetString("COMMANDS_QXR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /A-.
        /// </summary>
        internal static string COMMANDS_SLASH_A_INDENT {
            get {
                return ResourceManager.GetString("COMMANDS_SLASH_A_INDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /C-.
        /// </summary>
        internal static string COMMANDS_SLASH_C_INDENT {
            get {
                return ResourceManager.GetString("COMMANDS_SLASH_C_INDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /DELETE.
        /// </summary>
        internal static string COMMANDS_SLASH_DELETE {
            get {
                return ResourceManager.GetString("COMMANDS_SLASH_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /L.
        /// </summary>
        internal static string COMMANDS_SLASH_L {
            get {
                return ResourceManager.GetString("COMMANDS_SLASH_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYS.
        /// </summary>
        internal static string COMMANDS_SYS {
            get {
                return ResourceManager.GetString("COMMANDS_SYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string DOT {
            get {
                return ResourceManager.GetString("DOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string INDENT {
            get {
                return ResourceManager.GetString("INDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‡.
        /// </summary>
        internal static string LORRAINE_CROSS {
            get {
                return ResourceManager.GetString("LORRAINE_CROSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 511.
        /// </summary>
        internal static string QUEUE_511 {
            get {
                return ResourceManager.GetString("QUEUE_511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string SLASH {
            get {
                return ResourceManager.GetString("SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucAccountsRecordQueues.
        /// </summary>
        internal static string UC_ACCOUNTS_RECORD_QUEUES {
            get {
                return ResourceManager.GetString("UC_ACCOUNTS_RECORD_QUEUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucAdvancePNRQueue.
        /// </summary>
        internal static string UC_ADVANCE_PNR_QUEUE {
            get {
                return ResourceManager.GetString("UC_ADVANCE_PNR_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucEnterToQueue.
        /// </summary>
        internal static string UC_ENTER_TO_QUEUE {
            get {
                return ResourceManager.GetString("UC_ENTER_TO_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucExitFromQueue.
        /// </summary>
        internal static string UC_EXIT_FROM_QUEUE {
            get {
                return ResourceManager.GetString("UC_EXIT_FROM_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucHistoryRecordInQueue.
        /// </summary>
        internal static string UC_HISTORY_RECORD_IN_QUEUE {
            get {
                return ResourceManager.GetString("UC_HISTORY_RECORD_IN_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucHistoryRecordQueue.
        /// </summary>
        internal static string UC_HISTORY_RECORD_QUEUE {
            get {
                return ResourceManager.GetString("UC_HISTORY_RECORD_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucListRecordsQueue.
        /// </summary>
        internal static string UC_LIST_RECORDS_QUEUE {
            get {
                return ResourceManager.GetString("UC_LIST_RECORDS_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucMoveRecordsTweenQueues.
        /// </summary>
        internal static string UC_MOVE_RECORDS_TWEEN_QUEUES {
            get {
                return ResourceManager.GetString("UC_MOVE_RECORDS_TWEEN_QUEUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucPlaceRecordQueue.
        /// </summary>
        internal static string UC_PLACE_RECORD_QUEUE {
            get {
                return ResourceManager.GetString("UC_PLACE_RECORD_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucWorkingPNRinQueue.
        /// </summary>
        internal static string UC_WORKING_PNR_IN_QUEUE {
            get {
                return ResourceManager.GetString("UC_WORKING_PNR_IN_QUEUE", resourceCulture);
            }
        }
    }
}
