CREATE TABLE [dbo].[R_CLUSTER_SLAVE] (
    [ID_CLUSTER_SLAVE] BIGINT NOT NULL,
    [ID_CLUSTER]       INT    NULL,
    [ID_SLAVE]         INT    NULL,
    PRIMARY KEY CLUSTERED ([ID_CLUSTER_SLAVE] ASC)
);

