CREATE TABLE [dbo].[R_DATABASE_ATTRIBUTE] (
    [ID_DATABASE_ATTRIBUTE] BIGINT        NOT NULL,
    [ID_DATABASE]           INT           NULL,
    [CODE]                  VARCHAR (255) NULL,
    [VALUE_STR]             TEXT          NULL,
    PRIMARY KEY CLUSTERED ([ID_DATABASE_ATTRIBUTE] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_R_DATABASE_ATTRIBUTE_AK]
    ON [dbo].[R_DATABASE_ATTRIBUTE]([ID_DATABASE] ASC, [CODE] ASC);

