CREATE TABLE [dbo].[R_DATABASE_CONTYPE] (
    [ID_DATABASE_CONTYPE] BIGINT        NOT NULL,
    [CODE]                VARCHAR (255) NULL,
    [DESCRIPTION]         VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID_DATABASE_CONTYPE] ASC)
);

