CREATE TABLE [dbo].[R_DATABASE_TYPE] (
    [ID_DATABASE_TYPE] BIGINT        NOT NULL,
    [CODE]             VARCHAR (255) NULL,
    [DESCRIPTION]      VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID_DATABASE_TYPE] ASC)
);

