CREATE TABLE [dbo].[R_DEPENDENCY] (
    [ID_DEPENDENCY]     BIGINT        NOT NULL,
    [ID_TRANSFORMATION] INT           NULL,
    [ID_DATABASE]       INT           NULL,
    [TABLE_NAME]        VARCHAR (255) NULL,
    [FIELD_NAME]        VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID_DEPENDENCY] ASC)
);

