CREATE TABLE [dbo].[R_JOBENTRY_DATABASE] (
    [ID_JOB]      INT NULL,
    [ID_JOBENTRY] INT NULL,
    [ID_DATABASE] INT NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_R_JOBENTRY_DATABASE_LU1]
    ON [dbo].[R_JOBENTRY_DATABASE]([ID_JOB] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_R_JOBENTRY_DATABASE_LU2]
    ON [dbo].[R_JOBENTRY_DATABASE]([ID_DATABASE] ASC);

