CREATE TABLE [dbo].[R_JOBENTRY_TYPE] (
    [ID_JOBENTRY_TYPE] BIGINT        NOT NULL,
    [CODE]             VARCHAR (255) NULL,
    [DESCRIPTION]      VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID_JOBENTRY_TYPE] ASC)
);

