CREATE TABLE [dbo].[R_LOGLEVEL] (
    [ID_LOGLEVEL] BIGINT        NOT NULL,
    [CODE]        VARCHAR (255) NULL,
    [DESCRIPTION] VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID_LOGLEVEL] ASC)
);

