CREATE TABLE [dbo].[R_PARTITION_SCHEMA] (
    [ID_PARTITION_SCHEMA]  BIGINT        NOT NULL,
    [NAME]                 VARCHAR (255) NULL,
    [DYNAMIC_DEFINITION]   CHAR (1)      NULL,
    [PARTITIONS_PER_SLAVE] VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID_PARTITION_SCHEMA] ASC)
);

