CREATE TABLE [dbo].[R_REPOSITORY_LOG] (
    [ID_REPOSITORY_LOG] BIGINT        NOT NULL,
    [REP_VERSION]       VARCHAR (255) NULL,
    [LOG_DATE]          DATETIME      NULL,
    [LOG_USER]          VARCHAR (255) NULL,
    [OPERATION_DESC]    TEXT          NULL,
    PRIMARY KEY CLUSTERED ([ID_REPOSITORY_LOG] ASC)
);

