CREATE TABLE [dbo].[R_STEP_TYPE] (
    [ID_STEP_TYPE] BIGINT        NOT NULL,
    [CODE]         VARCHAR (255) NULL,
    [DESCRIPTION]  VARCHAR (255) NULL,
    [HELPTEXT]     VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ID_STEP_TYPE] ASC)
);

