CREATE TABLE [dbo].[R_TRANS_PARTITION_SCHEMA] (
    [ID_TRANS_PARTITION_SCHEMA] BIGINT NOT NULL,
    [ID_TRANSFORMATION]         INT    NULL,
    [ID_PARTITION_SCHEMA]       INT    NULL,
    PRIMARY KEY CLUSTERED ([ID_TRANS_PARTITION_SCHEMA] ASC)
);

