CREATE TABLE [dbo].[R_TRANS_ATTRIBUTE] (
    [ID_TRANS_ATTRIBUTE] BIGINT        NOT NULL,
    [ID_TRANSFORMATION]  INT           NULL,
    [NR]                 INT           NULL,
    [CODE]               VARCHAR (255) NULL,
    [VALUE_NUM]          BIGINT        NULL,
    [VALUE_STR]          TEXT          NULL,
    PRIMARY KEY CLUSTERED ([ID_TRANS_ATTRIBUTE] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_TRANS_ATTRIBUTE_LOOKUP]
    ON [dbo].[R_TRANS_ATTRIBUTE]([ID_TRANSFORMATION] ASC, [CODE] ASC, [NR] ASC);

