CREATE TABLE [dbo].[R_TRANSFORMATION] (
    [ID_TRANSFORMATION]    BIGINT          NOT NULL,
    [ID_DIRECTORY]         INT             NULL,
    [NAME]                 VARCHAR (255)   NULL,
    [DESCRIPTION]          TEXT            NULL,
    [EXTENDED_DESCRIPTION] TEXT            NULL,
    [TRANS_VERSION]        VARCHAR (255)   NULL,
    [TRANS_STATUS]         INT             NULL,
    [ID_STEP_READ]         INT             NULL,
    [ID_STEP_WRITE]        INT             NULL,
    [ID_STEP_INPUT]        INT             NULL,
    [ID_STEP_OUTPUT]       INT             NULL,
    [ID_STEP_UPDATE]       INT             NULL,
    [ID_DATABASE_LOG]      INT             NULL,
    [TABLE_NAME_LOG]       VARCHAR (255)   NULL,
    [USE_BATCHID]          CHAR (1)        NULL,
    [USE_LOGFIELD]         CHAR (1)        NULL,
    [ID_DATABASE_MAXDATE]  INT             NULL,
    [TABLE_NAME_MAXDATE]   VARCHAR (255)   NULL,
    [FIELD_NAME_MAXDATE]   VARCHAR (255)   NULL,
    [OFFSET_MAXDATE]       DECIMAL (12, 2) NULL,
    [DIFF_MAXDATE]         DECIMAL (12, 2) NULL,
    [CREATED_USER]         VARCHAR (255)   NULL,
    [CREATED_DATE]         DATETIME        NULL,
    [MODIFIED_USER]        VARCHAR (255)   NULL,
    [MODIFIED_DATE]        DATETIME        NULL,
    [SIZE_ROWSET]          INT             NULL,
    PRIMARY KEY CLUSTERED ([ID_TRANSFORMATION] ASC)
);

