CREATE TABLE [dbo].[R_TRANS_CLUSTER] (
    [ID_TRANS_CLUSTER]  BIGINT NOT NULL,
    [ID_TRANSFORMATION] INT    NULL,
    [ID_CLUSTER]        INT    NULL,
    PRIMARY KEY CLUSTERED ([ID_TRANS_CLUSTER] ASC)
);

