CREATE TABLE [dbo].[R_VALUE] (
    [ID_VALUE]   BIGINT        NOT NULL,
    [NAME]       VARCHAR (255) NULL,
    [VALUE_TYPE] VARCHAR (255) NULL,
    [VALUE_STR]  VARCHAR (255) NULL,
    [IS_NULL]    CHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([ID_VALUE] ASC)
);

