CREATE TABLE [dbo].[R_VERSION] (
    [ID_VERSION]    BIGINT   NOT NULL,
    [MAJOR_VERSION] INT      NULL,
    [MINOR_VERSION] INT      NULL,
    [UPGRADE_DATE]  DATETIME NULL,
    [IS_UPGRADE]    CHAR (1) NULL,
    PRIMARY KEY CLUSTERED ([ID_VERSION] ASC)
);

