CREATE TABLE [dbo].[updateteva$] (
    [Worker Number]                          FLOAT (53)     NULL,
    [Global ID]                              NVARCHAR (255) NULL,
    [Person Name]                            NVARCHAR (255) NULL,
    [Employee Email Address]                 NVARCHAR (255) NULL,
    [Authorizer "1"  (Direct Manager_HRBI)]  NVARCHAR (255) NULL,
    [Authorizer "1"  (Direct Manager_HRBI)1] NVARCHAR (255) NULL,
    [Authorizer "2 " (BU Manager)]           NVARCHAR (255) NULL,
    [Authorizer "3" (TEC)]                   NVARCHAR (255) NULL,
    [CO CODE]                                FLOAT (53)     NULL,
    [SBU]                                    FLOAT (53)     NULL,
    [SITE_CODE]                              FLOAT (53)     NULL,
    [COST CENTER]                            FLOAT (53)     NULL,
    [OCC - Cost Center L1]                   FLOAT (53)     NULL,
    [Cost Center Meaning]                    NVARCHAR (255) NULL,
    [Organization Name]                      NVARCHAR (255) NULL,
    [Job Name]                               NVARCHAR (255) NULL,
    [Position Name]                          NVARCHAR (255) NULL,
    [Contract]                               NVARCHAR (255) NULL,
    [People Group]                           NVARCHAR (255) NULL,
    [Location Name]                          NVARCHAR (255) NULL,
    [Supervisor Name]                        NVARCHAR (255) NULL,
    [Hire Date]                              DATETIME       NULL,
    [Worker Type]                            NVARCHAR (255) NULL,
    [Status]                                 NVARCHAR (255) NULL,
    [FTE]                                    FLOAT (53)     NULL,
    [HC]                                     FLOAT (53)     NULL
);

