//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace MyCTS.Services.PagosMIT {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TransaccionesTarjetaNPServiceSoap", Namespace="http://tempuri.org/")]
    public partial class TransaccionesTarjetaNPService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CobroOperationCompleted;
        
        private System.Threading.SendOrPostCallback CobroMultiempresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SolicitudSDOSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumeroIntentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumeroTransaccionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificaNumeroAutorizacionOperacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback HistoricoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMotivoTransaccionPreviaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidatePaymentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TransaccionesTarjetaNPService() {
            this.Url = global::MyCTS.Services.Properties.Settings.Default.MyCTS_Services_PagosMIT_TransaccionesTarjetaNPService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CobroCompletedEventHandler CobroCompleted;
        
        /// <remarks/>
        public event CobroMultiempresaCompletedEventHandler CobroMultiempresaCompleted;
        
        /// <remarks/>
        public event CancelacionCompletedEventHandler CancelacionCompleted;
        
        /// <remarks/>
        public event SolicitudSDOSCompletedEventHandler SolicitudSDOSCompleted;
        
        /// <remarks/>
        public event GetNumeroIntentosCompletedEventHandler GetNumeroIntentosCompleted;
        
        /// <remarks/>
        public event GetNumeroTransaccionesCompletedEventHandler GetNumeroTransaccionesCompleted;
        
        /// <remarks/>
        public event VerificaNumeroAutorizacionOperacionCompletedEventHandler VerificaNumeroAutorizacionOperacionCompleted;
        
        /// <remarks/>
        public event HistoricoCompletedEventHandler HistoricoCompleted;
        
        /// <remarks/>
        public event GetMotivoTransaccionPreviaCompletedEventHandler GetMotivoTransaccionPreviaCompleted;
        
        /// <remarks/>
        public event ValidatePaymentCompletedEventHandler ValidatePaymentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Cobro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Cobro(string sReferencia, string sNombre, string sNumero, string sMesExpira, string sAnioExpira, string sCodigoSeguridad, decimal dMonto, string sCurrency, string sTipoTarjeta, string sMerchant, ref TransaccionesRespuestasEntities respuesta) {
            object[] results = this.Invoke("Cobro", new object[] {
                        sReferencia,
                        sNombre,
                        sNumero,
                        sMesExpira,
                        sAnioExpira,
                        sCodigoSeguridad,
                        dMonto,
                        sCurrency,
                        sTipoTarjeta,
                        sMerchant,
                        respuesta});
            respuesta = ((TransaccionesRespuestasEntities)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CobroAsync(string sReferencia, string sNombre, string sNumero, string sMesExpira, string sAnioExpira, string sCodigoSeguridad, decimal dMonto, string sCurrency, string sTipoTarjeta, string sMerchant, TransaccionesRespuestasEntities respuesta) {
            this.CobroAsync(sReferencia, sNombre, sNumero, sMesExpira, sAnioExpira, sCodigoSeguridad, dMonto, sCurrency, sTipoTarjeta, sMerchant, respuesta, null);
        }
        
        /// <remarks/>
        public void CobroAsync(string sReferencia, string sNombre, string sNumero, string sMesExpira, string sAnioExpira, string sCodigoSeguridad, decimal dMonto, string sCurrency, string sTipoTarjeta, string sMerchant, TransaccionesRespuestasEntities respuesta, object userState) {
            if ((this.CobroOperationCompleted == null)) {
                this.CobroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCobroOperationCompleted);
            }
            this.InvokeAsync("Cobro", new object[] {
                        sReferencia,
                        sNombre,
                        sNumero,
                        sMesExpira,
                        sAnioExpira,
                        sCodigoSeguridad,
                        dMonto,
                        sCurrency,
                        sTipoTarjeta,
                        sMerchant,
                        respuesta}, this.CobroOperationCompleted, userState);
        }
        
        private void OnCobroOperationCompleted(object arg) {
            if ((this.CobroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CobroCompleted(this, new CobroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CobroMultiempresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CobroMultiempresa(string sReferencia, string sNombre, string sNumero, string sMesExpira, string sAnioExpira, string sCodigoSeguridad, decimal dMonto, string sCurrency, string sTipoTarjeta, string sMerchant, int organizacionId, ref TransaccionesRespuestasEntities respuesta) {
            object[] results = this.Invoke("CobroMultiempresa", new object[] {
                        sReferencia,
                        sNombre,
                        sNumero,
                        sMesExpira,
                        sAnioExpira,
                        sCodigoSeguridad,
                        dMonto,
                        sCurrency,
                        sTipoTarjeta,
                        sMerchant,
                        organizacionId,
                        respuesta});
            respuesta = ((TransaccionesRespuestasEntities)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CobroMultiempresaAsync(string sReferencia, string sNombre, string sNumero, string sMesExpira, string sAnioExpira, string sCodigoSeguridad, decimal dMonto, string sCurrency, string sTipoTarjeta, string sMerchant, int organizacionId, TransaccionesRespuestasEntities respuesta) {
            this.CobroMultiempresaAsync(sReferencia, sNombre, sNumero, sMesExpira, sAnioExpira, sCodigoSeguridad, dMonto, sCurrency, sTipoTarjeta, sMerchant, organizacionId, respuesta, null);
        }
        
        /// <remarks/>
        public void CobroMultiempresaAsync(string sReferencia, string sNombre, string sNumero, string sMesExpira, string sAnioExpira, string sCodigoSeguridad, decimal dMonto, string sCurrency, string sTipoTarjeta, string sMerchant, int organizacionId, TransaccionesRespuestasEntities respuesta, object userState) {
            if ((this.CobroMultiempresaOperationCompleted == null)) {
                this.CobroMultiempresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCobroMultiempresaOperationCompleted);
            }
            this.InvokeAsync("CobroMultiempresa", new object[] {
                        sReferencia,
                        sNombre,
                        sNumero,
                        sMesExpira,
                        sAnioExpira,
                        sCodigoSeguridad,
                        dMonto,
                        sCurrency,
                        sTipoTarjeta,
                        sMerchant,
                        organizacionId,
                        respuesta}, this.CobroMultiempresaOperationCompleted, userState);
        }
        
        private void OnCobroMultiempresaOperationCompleted(object arg) {
            if ((this.CobroMultiempresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CobroMultiempresaCompleted(this, new CobroMultiempresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Cancelacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Cancelacion(string sReference, decimal dMonto, string sNoOperacion, string sAutorizacion, ref TransaccionesRespuestasEntities respuesta) {
            object[] results = this.Invoke("Cancelacion", new object[] {
                        sReference,
                        dMonto,
                        sNoOperacion,
                        sAutorizacion,
                        respuesta});
            respuesta = ((TransaccionesRespuestasEntities)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelacionAsync(string sReference, decimal dMonto, string sNoOperacion, string sAutorizacion, TransaccionesRespuestasEntities respuesta) {
            this.CancelacionAsync(sReference, dMonto, sNoOperacion, sAutorizacion, respuesta, null);
        }
        
        /// <remarks/>
        public void CancelacionAsync(string sReference, decimal dMonto, string sNoOperacion, string sAutorizacion, TransaccionesRespuestasEntities respuesta, object userState) {
            if ((this.CancelacionOperationCompleted == null)) {
                this.CancelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelacionOperationCompleted);
            }
            this.InvokeAsync("Cancelacion", new object[] {
                        sReference,
                        dMonto,
                        sNoOperacion,
                        sAutorizacion,
                        respuesta}, this.CancelacionOperationCompleted, userState);
        }
        
        private void OnCancelacionOperationCompleted(object arg) {
            if ((this.CancelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelacionCompleted(this, new CancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SolicitudSDOS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SolicitudSDOS(
                    string sReservacion, 
                    string sReferencia, 
                    string sMonto, 
                    string sCreditCardNumber, 
                    string sCreditCardExpMonth, 
                    string sCreditCardExpYear, 
                    string sBillingName, 
                    string sBillingStreet, 
                    string sBillingHouseNumber, 
                    string sBillingHouseNumberInt, 
                    string sBillingNeighborhood, 
                    string sBillingMunicipality, 
                    string sBillingCity, 
                    string sBillingState, 
                    string sBillingZipCode, 
                    string sBillingCountry, 
                    string sBillingPhone, 
                    string sBillingPhone2, 
                    string sBillingEMail, 
                    string sBrowserSessionID, 
                    string sBrowserHostName, 
                    string sBrowserAccept, 
                    string sBrowserAcceptEncoding, 
                    string sBrowserAcceptCharset, 
                    string sBrowserID, 
                    string sBrowserIDLanguageCode, 
                    string sBrowserIP, 
                    string sBrowserReferer, 
                    string sBrowserConnection, 
                    string sJavascriptData, 
                    ref TransaccionesRespuestasEntities respuesta) {
            object[] results = this.Invoke("SolicitudSDOS", new object[] {
                        sReservacion,
                        sReferencia,
                        sMonto,
                        sCreditCardNumber,
                        sCreditCardExpMonth,
                        sCreditCardExpYear,
                        sBillingName,
                        sBillingStreet,
                        sBillingHouseNumber,
                        sBillingHouseNumberInt,
                        sBillingNeighborhood,
                        sBillingMunicipality,
                        sBillingCity,
                        sBillingState,
                        sBillingZipCode,
                        sBillingCountry,
                        sBillingPhone,
                        sBillingPhone2,
                        sBillingEMail,
                        sBrowserSessionID,
                        sBrowserHostName,
                        sBrowserAccept,
                        sBrowserAcceptEncoding,
                        sBrowserAcceptCharset,
                        sBrowserID,
                        sBrowserIDLanguageCode,
                        sBrowserIP,
                        sBrowserReferer,
                        sBrowserConnection,
                        sJavascriptData,
                        respuesta});
            respuesta = ((TransaccionesRespuestasEntities)(results[0]));
        }
        
        /// <remarks/>
        public void SolicitudSDOSAsync(
                    string sReservacion, 
                    string sReferencia, 
                    string sMonto, 
                    string sCreditCardNumber, 
                    string sCreditCardExpMonth, 
                    string sCreditCardExpYear, 
                    string sBillingName, 
                    string sBillingStreet, 
                    string sBillingHouseNumber, 
                    string sBillingHouseNumberInt, 
                    string sBillingNeighborhood, 
                    string sBillingMunicipality, 
                    string sBillingCity, 
                    string sBillingState, 
                    string sBillingZipCode, 
                    string sBillingCountry, 
                    string sBillingPhone, 
                    string sBillingPhone2, 
                    string sBillingEMail, 
                    string sBrowserSessionID, 
                    string sBrowserHostName, 
                    string sBrowserAccept, 
                    string sBrowserAcceptEncoding, 
                    string sBrowserAcceptCharset, 
                    string sBrowserID, 
                    string sBrowserIDLanguageCode, 
                    string sBrowserIP, 
                    string sBrowserReferer, 
                    string sBrowserConnection, 
                    string sJavascriptData, 
                    TransaccionesRespuestasEntities respuesta) {
            this.SolicitudSDOSAsync(sReservacion, sReferencia, sMonto, sCreditCardNumber, sCreditCardExpMonth, sCreditCardExpYear, sBillingName, sBillingStreet, sBillingHouseNumber, sBillingHouseNumberInt, sBillingNeighborhood, sBillingMunicipality, sBillingCity, sBillingState, sBillingZipCode, sBillingCountry, sBillingPhone, sBillingPhone2, sBillingEMail, sBrowserSessionID, sBrowserHostName, sBrowserAccept, sBrowserAcceptEncoding, sBrowserAcceptCharset, sBrowserID, sBrowserIDLanguageCode, sBrowserIP, sBrowserReferer, sBrowserConnection, sJavascriptData, respuesta, null);
        }
        
        /// <remarks/>
        public void SolicitudSDOSAsync(
                    string sReservacion, 
                    string sReferencia, 
                    string sMonto, 
                    string sCreditCardNumber, 
                    string sCreditCardExpMonth, 
                    string sCreditCardExpYear, 
                    string sBillingName, 
                    string sBillingStreet, 
                    string sBillingHouseNumber, 
                    string sBillingHouseNumberInt, 
                    string sBillingNeighborhood, 
                    string sBillingMunicipality, 
                    string sBillingCity, 
                    string sBillingState, 
                    string sBillingZipCode, 
                    string sBillingCountry, 
                    string sBillingPhone, 
                    string sBillingPhone2, 
                    string sBillingEMail, 
                    string sBrowserSessionID, 
                    string sBrowserHostName, 
                    string sBrowserAccept, 
                    string sBrowserAcceptEncoding, 
                    string sBrowserAcceptCharset, 
                    string sBrowserID, 
                    string sBrowserIDLanguageCode, 
                    string sBrowserIP, 
                    string sBrowserReferer, 
                    string sBrowserConnection, 
                    string sJavascriptData, 
                    TransaccionesRespuestasEntities respuesta, 
                    object userState) {
            if ((this.SolicitudSDOSOperationCompleted == null)) {
                this.SolicitudSDOSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitudSDOSOperationCompleted);
            }
            this.InvokeAsync("SolicitudSDOS", new object[] {
                        sReservacion,
                        sReferencia,
                        sMonto,
                        sCreditCardNumber,
                        sCreditCardExpMonth,
                        sCreditCardExpYear,
                        sBillingName,
                        sBillingStreet,
                        sBillingHouseNumber,
                        sBillingHouseNumberInt,
                        sBillingNeighborhood,
                        sBillingMunicipality,
                        sBillingCity,
                        sBillingState,
                        sBillingZipCode,
                        sBillingCountry,
                        sBillingPhone,
                        sBillingPhone2,
                        sBillingEMail,
                        sBrowserSessionID,
                        sBrowserHostName,
                        sBrowserAccept,
                        sBrowserAcceptEncoding,
                        sBrowserAcceptCharset,
                        sBrowserID,
                        sBrowserIDLanguageCode,
                        sBrowserIP,
                        sBrowserReferer,
                        sBrowserConnection,
                        sJavascriptData,
                        respuesta}, this.SolicitudSDOSOperationCompleted, userState);
        }
        
        private void OnSolicitudSDOSOperationCompleted(object arg) {
            if ((this.SolicitudSDOSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitudSDOSCompleted(this, new SolicitudSDOSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumeroIntentos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetNumeroIntentos(string sReservacion, int orgId) {
            object[] results = this.Invoke("GetNumeroIntentos", new object[] {
                        sReservacion,
                        orgId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumeroIntentosAsync(string sReservacion, int orgId) {
            this.GetNumeroIntentosAsync(sReservacion, orgId, null);
        }
        
        /// <remarks/>
        public void GetNumeroIntentosAsync(string sReservacion, int orgId, object userState) {
            if ((this.GetNumeroIntentosOperationCompleted == null)) {
                this.GetNumeroIntentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumeroIntentosOperationCompleted);
            }
            this.InvokeAsync("GetNumeroIntentos", new object[] {
                        sReservacion,
                        orgId}, this.GetNumeroIntentosOperationCompleted, userState);
        }
        
        private void OnGetNumeroIntentosOperationCompleted(object arg) {
            if ((this.GetNumeroIntentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumeroIntentosCompleted(this, new GetNumeroIntentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumeroTransacciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetNumeroTransacciones(string sReservacion, int orgId) {
            object[] results = this.Invoke("GetNumeroTransacciones", new object[] {
                        sReservacion,
                        orgId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumeroTransaccionesAsync(string sReservacion, int orgId) {
            this.GetNumeroTransaccionesAsync(sReservacion, orgId, null);
        }
        
        /// <remarks/>
        public void GetNumeroTransaccionesAsync(string sReservacion, int orgId, object userState) {
            if ((this.GetNumeroTransaccionesOperationCompleted == null)) {
                this.GetNumeroTransaccionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumeroTransaccionesOperationCompleted);
            }
            this.InvokeAsync("GetNumeroTransacciones", new object[] {
                        sReservacion,
                        orgId}, this.GetNumeroTransaccionesOperationCompleted, userState);
        }
        
        private void OnGetNumeroTransaccionesOperationCompleted(object arg) {
            if ((this.GetNumeroTransaccionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumeroTransaccionesCompleted(this, new GetNumeroTransaccionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificaNumeroAutorizacionOperacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerificaNumeroAutorizacionOperacion(string sReservacion) {
            object[] results = this.Invoke("VerificaNumeroAutorizacionOperacion", new object[] {
                        sReservacion});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerificaNumeroAutorizacionOperacionAsync(string sReservacion) {
            this.VerificaNumeroAutorizacionOperacionAsync(sReservacion, null);
        }
        
        /// <remarks/>
        public void VerificaNumeroAutorizacionOperacionAsync(string sReservacion, object userState) {
            if ((this.VerificaNumeroAutorizacionOperacionOperationCompleted == null)) {
                this.VerificaNumeroAutorizacionOperacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificaNumeroAutorizacionOperacionOperationCompleted);
            }
            this.InvokeAsync("VerificaNumeroAutorizacionOperacion", new object[] {
                        sReservacion}, this.VerificaNumeroAutorizacionOperacionOperationCompleted, userState);
        }
        
        private void OnVerificaNumeroAutorizacionOperacionOperationCompleted(object arg) {
            if ((this.VerificaNumeroAutorizacionOperacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificaNumeroAutorizacionOperacionCompleted(this, new VerificaNumeroAutorizacionOperacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Historico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioTransaccionesEntities[] Historico(string sReferencia, int orgId) {
            object[] results = this.Invoke("Historico", new object[] {
                        sReferencia,
                        orgId});
            return ((UsuarioTransaccionesEntities[])(results[0]));
        }
        
        /// <remarks/>
        public void HistoricoAsync(string sReferencia, int orgId) {
            this.HistoricoAsync(sReferencia, orgId, null);
        }
        
        /// <remarks/>
        public void HistoricoAsync(string sReferencia, int orgId, object userState) {
            if ((this.HistoricoOperationCompleted == null)) {
                this.HistoricoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHistoricoOperationCompleted);
            }
            this.InvokeAsync("Historico", new object[] {
                        sReferencia,
                        orgId}, this.HistoricoOperationCompleted, userState);
        }
        
        private void OnHistoricoOperationCompleted(object arg) {
            if ((this.HistoricoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HistoricoCompleted(this, new HistoricoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMotivoTransaccionPrevia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMotivoTransaccionPrevia(System.DateTime dtFechaConsulta) {
            object[] results = this.Invoke("GetMotivoTransaccionPrevia", new object[] {
                        dtFechaConsulta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMotivoTransaccionPreviaAsync(System.DateTime dtFechaConsulta) {
            this.GetMotivoTransaccionPreviaAsync(dtFechaConsulta, null);
        }
        
        /// <remarks/>
        public void GetMotivoTransaccionPreviaAsync(System.DateTime dtFechaConsulta, object userState) {
            if ((this.GetMotivoTransaccionPreviaOperationCompleted == null)) {
                this.GetMotivoTransaccionPreviaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMotivoTransaccionPreviaOperationCompleted);
            }
            this.InvokeAsync("GetMotivoTransaccionPrevia", new object[] {
                        dtFechaConsulta}, this.GetMotivoTransaccionPreviaOperationCompleted, userState);
        }
        
        private void OnGetMotivoTransaccionPreviaOperationCompleted(object arg) {
            if ((this.GetMotivoTransaccionPreviaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMotivoTransaccionPreviaCompleted(this, new GetMotivoTransaccionPreviaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidatePayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidatePayment(ref TransaccionesEntities tran, System.DateTime dtFechaConsulta) {
            object[] results = this.Invoke("ValidatePayment", new object[] {
                        tran,
                        dtFechaConsulta});
            tran = ((TransaccionesEntities)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidatePaymentAsync(TransaccionesEntities tran, System.DateTime dtFechaConsulta) {
            this.ValidatePaymentAsync(tran, dtFechaConsulta, null);
        }
        
        /// <remarks/>
        public void ValidatePaymentAsync(TransaccionesEntities tran, System.DateTime dtFechaConsulta, object userState) {
            if ((this.ValidatePaymentOperationCompleted == null)) {
                this.ValidatePaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidatePaymentOperationCompleted);
            }
            this.InvokeAsync("ValidatePayment", new object[] {
                        tran,
                        dtFechaConsulta}, this.ValidatePaymentOperationCompleted, userState);
        }
        
        private void OnValidatePaymentOperationCompleted(object arg) {
            if ((this.ValidatePaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidatePaymentCompleted(this, new ValidatePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransaccionesRespuestasEntities {
        
        private string estatusTransaccionField;
        
        private string mensajeAmistosoField;
        
        private string numeroOperacionField;
        
        private string numeroAutorizacionField;
        
        /// <remarks/>
        public string EstatusTransaccion {
            get {
                return this.estatusTransaccionField;
            }
            set {
                this.estatusTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeAmistoso {
            get {
                return this.mensajeAmistosoField;
            }
            set {
                this.mensajeAmistosoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroOperacion {
            get {
                return this.numeroOperacionField;
            }
            set {
                this.numeroOperacionField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroAutorizacion {
            get {
                return this.numeroAutorizacionField;
            }
            set {
                this.numeroAutorizacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransaccionesEntities {
        
        private string sCompanyIdField;
        
        private string sBranchIdField;
        
        private string sCountryField;
        
        private string sMerchantField;
        
        private string sReferenceField;
        
        private string sTpOperacionField;
        
        private string sUsrTransacctionField;
        
        private decimal dAmountField;
        
        private string sCurrencyField;
        
        private string sVersionField;
        
        private string sTypeField;
        
        private string sNameField;
        
        private string sNumberField;
        
        private string sExpMonthField;
        
        private string sExpYearField;
        
        private string sCvvCscField;
        
        private string sAuthField;
        
        private string sNoOperacionField;
        
        private string sPeticionField;
        
        private string sRespuestaField;
        
        private string sResumenField;
        
        private byte bRoomField;
        
        private int iCryptoField;
        
        private int iTransaccionIDField;
        
        /// <remarks/>
        public string sCompanyId {
            get {
                return this.sCompanyIdField;
            }
            set {
                this.sCompanyIdField = value;
            }
        }
        
        /// <remarks/>
        public string sBranchId {
            get {
                return this.sBranchIdField;
            }
            set {
                this.sBranchIdField = value;
            }
        }
        
        /// <remarks/>
        public string sCountry {
            get {
                return this.sCountryField;
            }
            set {
                this.sCountryField = value;
            }
        }
        
        /// <remarks/>
        public string sMerchant {
            get {
                return this.sMerchantField;
            }
            set {
                this.sMerchantField = value;
            }
        }
        
        /// <remarks/>
        public string sReference {
            get {
                return this.sReferenceField;
            }
            set {
                this.sReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string sTpOperacion {
            get {
                return this.sTpOperacionField;
            }
            set {
                this.sTpOperacionField = value;
            }
        }
        
        /// <remarks/>
        public string sUsrTransacction {
            get {
                return this.sUsrTransacctionField;
            }
            set {
                this.sUsrTransacctionField = value;
            }
        }
        
        /// <remarks/>
        public decimal dAmount {
            get {
                return this.dAmountField;
            }
            set {
                this.dAmountField = value;
            }
        }
        
        /// <remarks/>
        public string sCurrency {
            get {
                return this.sCurrencyField;
            }
            set {
                this.sCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public string sVersion {
            get {
                return this.sVersionField;
            }
            set {
                this.sVersionField = value;
            }
        }
        
        /// <remarks/>
        public string sType {
            get {
                return this.sTypeField;
            }
            set {
                this.sTypeField = value;
            }
        }
        
        /// <remarks/>
        public string sName {
            get {
                return this.sNameField;
            }
            set {
                this.sNameField = value;
            }
        }
        
        /// <remarks/>
        public string sNumber {
            get {
                return this.sNumberField;
            }
            set {
                this.sNumberField = value;
            }
        }
        
        /// <remarks/>
        public string sExpMonth {
            get {
                return this.sExpMonthField;
            }
            set {
                this.sExpMonthField = value;
            }
        }
        
        /// <remarks/>
        public string sExpYear {
            get {
                return this.sExpYearField;
            }
            set {
                this.sExpYearField = value;
            }
        }
        
        /// <remarks/>
        public string sCvvCsc {
            get {
                return this.sCvvCscField;
            }
            set {
                this.sCvvCscField = value;
            }
        }
        
        /// <remarks/>
        public string sAuth {
            get {
                return this.sAuthField;
            }
            set {
                this.sAuthField = value;
            }
        }
        
        /// <remarks/>
        public string sNoOperacion {
            get {
                return this.sNoOperacionField;
            }
            set {
                this.sNoOperacionField = value;
            }
        }
        
        /// <remarks/>
        public string sPeticion {
            get {
                return this.sPeticionField;
            }
            set {
                this.sPeticionField = value;
            }
        }
        
        /// <remarks/>
        public string sRespuesta {
            get {
                return this.sRespuestaField;
            }
            set {
                this.sRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string sResumen {
            get {
                return this.sResumenField;
            }
            set {
                this.sResumenField = value;
            }
        }
        
        /// <remarks/>
        public byte bRoom {
            get {
                return this.bRoomField;
            }
            set {
                this.bRoomField = value;
            }
        }
        
        /// <remarks/>
        public int iCrypto {
            get {
                return this.iCryptoField;
            }
            set {
                this.iCryptoField = value;
            }
        }
        
        /// <remarks/>
        public int iTransaccionID {
            get {
                return this.iTransaccionIDField;
            }
            set {
                this.iTransaccionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioTransaccionesEntities {
        
        private string sDescripcionField;
        
        private string sFechaRegistroField;
        
        private string sNumeroAutorizacionField;
        
        private string sNumeroOperacionField;
        
        private string sMontoField;
        
        private string sResumenField;
        
        /// <remarks/>
        public string sDescripcion {
            get {
                return this.sDescripcionField;
            }
            set {
                this.sDescripcionField = value;
            }
        }
        
        /// <remarks/>
        public string sFechaRegistro {
            get {
                return this.sFechaRegistroField;
            }
            set {
                this.sFechaRegistroField = value;
            }
        }
        
        /// <remarks/>
        public string sNumeroAutorizacion {
            get {
                return this.sNumeroAutorizacionField;
            }
            set {
                this.sNumeroAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        public string sNumeroOperacion {
            get {
                return this.sNumeroOperacionField;
            }
            set {
                this.sNumeroOperacionField = value;
            }
        }
        
        /// <remarks/>
        public string sMonto {
            get {
                return this.sMontoField;
            }
            set {
                this.sMontoField = value;
            }
        }
        
        /// <remarks/>
        public string sResumen {
            get {
                return this.sResumenField;
            }
            set {
                this.sResumenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CobroCompletedEventHandler(object sender, CobroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CobroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CobroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TransaccionesRespuestasEntities respuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransaccionesRespuestasEntities)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CobroMultiempresaCompletedEventHandler(object sender, CobroMultiempresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CobroMultiempresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CobroMultiempresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TransaccionesRespuestasEntities respuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransaccionesRespuestasEntities)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CancelacionCompletedEventHandler(object sender, CancelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TransaccionesRespuestasEntities respuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransaccionesRespuestasEntities)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SolicitudSDOSCompletedEventHandler(object sender, SolicitudSDOSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolicitudSDOSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SolicitudSDOSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransaccionesRespuestasEntities respuesta {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransaccionesRespuestasEntities)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetNumeroIntentosCompletedEventHandler(object sender, GetNumeroIntentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumeroIntentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumeroIntentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetNumeroTransaccionesCompletedEventHandler(object sender, GetNumeroTransaccionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumeroTransaccionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumeroTransaccionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void VerificaNumeroAutorizacionOperacionCompletedEventHandler(object sender, VerificaNumeroAutorizacionOperacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificaNumeroAutorizacionOperacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificaNumeroAutorizacionOperacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HistoricoCompletedEventHandler(object sender, HistoricoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HistoricoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HistoricoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioTransaccionesEntities[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioTransaccionesEntities[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetMotivoTransaccionPreviaCompletedEventHandler(object sender, GetMotivoTransaccionPreviaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMotivoTransaccionPreviaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMotivoTransaccionPreviaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ValidatePaymentCompletedEventHandler(object sender, ValidatePaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidatePaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidatePaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TransaccionesEntities tran {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransaccionesEntities)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591