//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace MyCTS.Services.BuildElectronicTicket {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MailProviderSoap", Namespace="http://tempuri.org/")]
    public partial class MailProvider : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuildPDFDocumentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoTicketByTicketNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoPassengerByTicketNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfoPassengerByPNROperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTicketsByPNROperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendPDFDocumentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback EncryptOperationCompleted;
        
        private System.Threading.SendOrPostCallback DecryptOperationCompleted;
        
        private System.Threading.SendOrPostCallback WSTestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MailProvider() {
            this.Url = global::MyCTS.Services.Properties.Settings.Default.MyCTS_Services_BuildElectronicTicket_MailProvider;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuildPDFDocumentsCompletedEventHandler BuildPDFDocumentsCompleted;
        
        /// <remarks/>
        public event GetInfoTicketByTicketNumberCompletedEventHandler GetInfoTicketByTicketNumberCompleted;
        
        /// <remarks/>
        public event GetInfoPassengerByTicketNumberCompletedEventHandler GetInfoPassengerByTicketNumberCompleted;
        
        /// <remarks/>
        public event GetInfoPassengerByPNRCompletedEventHandler GetInfoPassengerByPNRCompleted;
        
        /// <remarks/>
        public event GetTicketsByPNRCompletedEventHandler GetTicketsByPNRCompleted;
        
        /// <remarks/>
        public event SendEmailCompletedEventHandler SendEmailCompleted;
        
        /// <remarks/>
        public event SendPDFDocumentsCompletedEventHandler SendPDFDocumentsCompleted;
        
        /// <remarks/>
        public event EncryptCompletedEventHandler EncryptCompleted;
        
        /// <remarks/>
        public event DecryptCompletedEventHandler DecryptCompleted;
        
        /// <remarks/>
        public event WSTestCompletedEventHandler WSTestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuildPDFDocuments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BuildPDFDocuments(string[] ticketNumber, string[] urlVirtuallyThere, string airline, string from, string password, string to, string displayName) {
            this.Invoke("BuildPDFDocuments", new object[] {
                        ticketNumber,
                        urlVirtuallyThere,
                        airline,
                        from,
                        password,
                        to,
                        displayName});
        }
        
        /// <remarks/>
        public void BuildPDFDocumentsAsync(string[] ticketNumber, string[] urlVirtuallyThere, string airline, string from, string password, string to, string displayName) {
            this.BuildPDFDocumentsAsync(ticketNumber, urlVirtuallyThere, airline, from, password, to, displayName, null);
        }
        
        /// <remarks/>
        public void BuildPDFDocumentsAsync(string[] ticketNumber, string[] urlVirtuallyThere, string airline, string from, string password, string to, string displayName, object userState) {
            if ((this.BuildPDFDocumentsOperationCompleted == null)) {
                this.BuildPDFDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuildPDFDocumentsOperationCompleted);
            }
            this.InvokeAsync("BuildPDFDocuments", new object[] {
                        ticketNumber,
                        urlVirtuallyThere,
                        airline,
                        from,
                        password,
                        to,
                        displayName}, this.BuildPDFDocumentsOperationCompleted, userState);
        }
        
        private void OnBuildPDFDocumentsOperationCompleted(object arg) {
            if ((this.BuildPDFDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuildPDFDocumentsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfoTicketByTicketNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TicketInformationObject GetInfoTicketByTicketNumber(string ticketNumber) {
            object[] results = this.Invoke("GetInfoTicketByTicketNumber", new object[] {
                        ticketNumber});
            return ((TicketInformationObject)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoTicketByTicketNumberAsync(string ticketNumber) {
            this.GetInfoTicketByTicketNumberAsync(ticketNumber, null);
        }
        
        /// <remarks/>
        public void GetInfoTicketByTicketNumberAsync(string ticketNumber, object userState) {
            if ((this.GetInfoTicketByTicketNumberOperationCompleted == null)) {
                this.GetInfoTicketByTicketNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoTicketByTicketNumberOperationCompleted);
            }
            this.InvokeAsync("GetInfoTicketByTicketNumber", new object[] {
                        ticketNumber}, this.GetInfoTicketByTicketNumberOperationCompleted, userState);
        }
        
        private void OnGetInfoTicketByTicketNumberOperationCompleted(object arg) {
            if ((this.GetInfoTicketByTicketNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoTicketByTicketNumberCompleted(this, new GetInfoTicketByTicketNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfoPassengerByTicketNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObjectTicketByPNR GetInfoPassengerByTicketNumber(string ticketNumber) {
            object[] results = this.Invoke("GetInfoPassengerByTicketNumber", new object[] {
                        ticketNumber});
            return ((ObjectTicketByPNR)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoPassengerByTicketNumberAsync(string ticketNumber) {
            this.GetInfoPassengerByTicketNumberAsync(ticketNumber, null);
        }
        
        /// <remarks/>
        public void GetInfoPassengerByTicketNumberAsync(string ticketNumber, object userState) {
            if ((this.GetInfoPassengerByTicketNumberOperationCompleted == null)) {
                this.GetInfoPassengerByTicketNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoPassengerByTicketNumberOperationCompleted);
            }
            this.InvokeAsync("GetInfoPassengerByTicketNumber", new object[] {
                        ticketNumber}, this.GetInfoPassengerByTicketNumberOperationCompleted, userState);
        }
        
        private void OnGetInfoPassengerByTicketNumberOperationCompleted(object arg) {
            if ((this.GetInfoPassengerByTicketNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoPassengerByTicketNumberCompleted(this, new GetInfoPassengerByTicketNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfoPassengerByPNR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ObjectTicketByPNR GetInfoPassengerByPNR(string sRecLoc) {
            object[] results = this.Invoke("GetInfoPassengerByPNR", new object[] {
                        sRecLoc});
            return ((ObjectTicketByPNR)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfoPassengerByPNRAsync(string sRecLoc) {
            this.GetInfoPassengerByPNRAsync(sRecLoc, null);
        }
        
        /// <remarks/>
        public void GetInfoPassengerByPNRAsync(string sRecLoc, object userState) {
            if ((this.GetInfoPassengerByPNROperationCompleted == null)) {
                this.GetInfoPassengerByPNROperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoPassengerByPNROperationCompleted);
            }
            this.InvokeAsync("GetInfoPassengerByPNR", new object[] {
                        sRecLoc}, this.GetInfoPassengerByPNROperationCompleted, userState);
        }
        
        private void OnGetInfoPassengerByPNROperationCompleted(object arg) {
            if ((this.GetInfoPassengerByPNRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfoPassengerByPNRCompleted(this, new GetInfoPassengerByPNRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTicketsByPNR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetTicketsByPNR(string sRecLoc) {
            object[] results = this.Invoke("GetTicketsByPNR", new object[] {
                        sRecLoc});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTicketsByPNRAsync(string sRecLoc) {
            this.GetTicketsByPNRAsync(sRecLoc, null);
        }
        
        /// <remarks/>
        public void GetTicketsByPNRAsync(string sRecLoc, object userState) {
            if ((this.GetTicketsByPNROperationCompleted == null)) {
                this.GetTicketsByPNROperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTicketsByPNROperationCompleted);
            }
            this.InvokeAsync("GetTicketsByPNR", new object[] {
                        sRecLoc}, this.GetTicketsByPNROperationCompleted, userState);
        }
        
        private void OnGetTicketsByPNROperationCompleted(object arg) {
            if ((this.GetTicketsByPNRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTicketsByPNRCompleted(this, new GetTicketsByPNRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendEmail(string from, string password, string displayName, string to, string cc, string subject, string body, string document, bool isHTMLFormat) {
            this.Invoke("SendEmail", new object[] {
                        from,
                        password,
                        displayName,
                        to,
                        cc,
                        subject,
                        body,
                        document,
                        isHTMLFormat});
        }
        
        /// <remarks/>
        public void SendEmailAsync(string from, string password, string displayName, string to, string cc, string subject, string body, string document, bool isHTMLFormat) {
            this.SendEmailAsync(from, password, displayName, to, cc, subject, body, document, isHTMLFormat, null);
        }
        
        /// <remarks/>
        public void SendEmailAsync(string from, string password, string displayName, string to, string cc, string subject, string body, string document, bool isHTMLFormat, object userState) {
            if ((this.SendEmailOperationCompleted == null)) {
                this.SendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailOperationCompleted);
            }
            this.InvokeAsync("SendEmail", new object[] {
                        from,
                        password,
                        displayName,
                        to,
                        cc,
                        subject,
                        body,
                        document,
                        isHTMLFormat}, this.SendEmailOperationCompleted, userState);
        }
        
        private void OnSendEmailOperationCompleted(object arg) {
            if ((this.SendEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendPDFDocuments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendPDFDocuments(string ticket, string mail, string ccMail, string urlVirtuallyThere, string from, string pass, string displayName) {
            this.Invoke("SendPDFDocuments", new object[] {
                        ticket,
                        mail,
                        ccMail,
                        urlVirtuallyThere,
                        from,
                        pass,
                        displayName});
        }
        
        /// <remarks/>
        public void SendPDFDocumentsAsync(string ticket, string mail, string ccMail, string urlVirtuallyThere, string from, string pass, string displayName) {
            this.SendPDFDocumentsAsync(ticket, mail, ccMail, urlVirtuallyThere, from, pass, displayName, null);
        }
        
        /// <remarks/>
        public void SendPDFDocumentsAsync(string ticket, string mail, string ccMail, string urlVirtuallyThere, string from, string pass, string displayName, object userState) {
            if ((this.SendPDFDocumentsOperationCompleted == null)) {
                this.SendPDFDocumentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendPDFDocumentsOperationCompleted);
            }
            this.InvokeAsync("SendPDFDocuments", new object[] {
                        ticket,
                        mail,
                        ccMail,
                        urlVirtuallyThere,
                        from,
                        pass,
                        displayName}, this.SendPDFDocumentsOperationCompleted, userState);
        }
        
        private void OnSendPDFDocumentsOperationCompleted(object arg) {
            if ((this.SendPDFDocumentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendPDFDocumentsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Encrypt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Encrypt(string Input) {
            object[] results = this.Invoke("Encrypt", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EncryptAsync(string Input) {
            this.EncryptAsync(Input, null);
        }
        
        /// <remarks/>
        public void EncryptAsync(string Input, object userState) {
            if ((this.EncryptOperationCompleted == null)) {
                this.EncryptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncryptOperationCompleted);
            }
            this.InvokeAsync("Encrypt", new object[] {
                        Input}, this.EncryptOperationCompleted, userState);
        }
        
        private void OnEncryptOperationCompleted(object arg) {
            if ((this.EncryptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncryptCompleted(this, new EncryptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Decrypt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Decrypt(string Input) {
            object[] results = this.Invoke("Decrypt", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DecryptAsync(string Input) {
            this.DecryptAsync(Input, null);
        }
        
        /// <remarks/>
        public void DecryptAsync(string Input, object userState) {
            if ((this.DecryptOperationCompleted == null)) {
                this.DecryptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDecryptOperationCompleted);
            }
            this.InvokeAsync("Decrypt", new object[] {
                        Input}, this.DecryptOperationCompleted, userState);
        }
        
        private void OnDecryptOperationCompleted(object arg) {
            if ((this.DecryptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DecryptCompleted(this, new DecryptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WSTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WSTest(string PNR) {
            object[] results = this.Invoke("WSTest", new object[] {
                        PNR});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WSTestAsync(string PNR) {
            this.WSTestAsync(PNR, null);
        }
        
        /// <remarks/>
        public void WSTestAsync(string PNR, object userState) {
            if ((this.WSTestOperationCompleted == null)) {
                this.WSTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWSTestOperationCompleted);
            }
            this.InvokeAsync("WSTest", new object[] {
                        PNR}, this.WSTestOperationCompleted, userState);
        }
        
        private void OnWSTestOperationCompleted(object arg) {
            if ((this.WSTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WSTestCompleted(this, new WSTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TicketInformationObject {
        
        private InformationSegment[] listItineraryInfoField;
        
        private string[] taxesListField;
        
        private string[] taxesList1Field;
        
        private int countField;
        
        private string responseField;
        
        private string recLocField;
        
        private string nameReferenceField;
        
        private string iataField;
        
        private string formOfPaymentField;
        
        private string formOfPaymentToTicketPrinterField;
        
        private string passengerNameField;
        
        private string passengerNameToElectronicTKTField;
        
        private string locationDKField;
        
        private string agencyCityField;
        
        private string rFCAirlineField;
        
        private string pCCField;
        
        private string agentField;
        
        private string tourCodeField;
        
        private bool statusField;
        
        private string baseFareField;
        
        private string totalTaxesField;
        
        private string totalField;
        
        private string currencyCodeBaseFareField;
        
        private string currencyCodeTotalField;
        
        private string fareCalculationField;
        
        private string equivFareField;
        
        private string currencyCodeEquivFareField;
        
        private bool paymentFormField;
        
        private string rFCAirline1Field;
        
        private string passengerNameCouponField;
        
        private string pNRField;
        
        private string iATANumberField;
        
        private string baseFare1Field;
        
        private string equivFare1Field;
        
        private string totalFareField;
        
        private string dateField;
        
        private string originField;
        
        private string destinationField;
        
        private string creditCardField;
        
        private string aPVLField;
        
        private string fareCalculation1Field;
        
        private string ticketModeField;
        
        private string conjunctiveTicketNumbersField;
        
        private string flightField;
        
        private string taxBreakField;
        
        private bool taxDownField;
        
        /// <remarks/>
        public InformationSegment[] listItineraryInfo {
            get {
                return this.listItineraryInfoField;
            }
            set {
                this.listItineraryInfoField = value;
            }
        }
        
        /// <remarks/>
        public string[] taxesList {
            get {
                return this.taxesListField;
            }
            set {
                this.taxesListField = value;
            }
        }
        
        /// <remarks/>
        public string[] taxesList1 {
            get {
                return this.taxesList1Field;
            }
            set {
                this.taxesList1Field = value;
            }
        }
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public string RecLoc {
            get {
                return this.recLocField;
            }
            set {
                this.recLocField = value;
            }
        }
        
        /// <remarks/>
        public string NameReference {
            get {
                return this.nameReferenceField;
            }
            set {
                this.nameReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string Iata {
            get {
                return this.iataField;
            }
            set {
                this.iataField = value;
            }
        }
        
        /// <remarks/>
        public string FormOfPayment {
            get {
                return this.formOfPaymentField;
            }
            set {
                this.formOfPaymentField = value;
            }
        }
        
        /// <remarks/>
        public string FormOfPaymentToTicketPrinter {
            get {
                return this.formOfPaymentToTicketPrinterField;
            }
            set {
                this.formOfPaymentToTicketPrinterField = value;
            }
        }
        
        /// <remarks/>
        public string PassengerName {
            get {
                return this.passengerNameField;
            }
            set {
                this.passengerNameField = value;
            }
        }
        
        /// <remarks/>
        public string PassengerNameToElectronicTKT {
            get {
                return this.passengerNameToElectronicTKTField;
            }
            set {
                this.passengerNameToElectronicTKTField = value;
            }
        }
        
        /// <remarks/>
        public string LocationDK {
            get {
                return this.locationDKField;
            }
            set {
                this.locationDKField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyCity {
            get {
                return this.agencyCityField;
            }
            set {
                this.agencyCityField = value;
            }
        }
        
        /// <remarks/>
        public string RFCAirline {
            get {
                return this.rFCAirlineField;
            }
            set {
                this.rFCAirlineField = value;
            }
        }
        
        /// <remarks/>
        public string PCC {
            get {
                return this.pCCField;
            }
            set {
                this.pCCField = value;
            }
        }
        
        /// <remarks/>
        public string Agent {
            get {
                return this.agentField;
            }
            set {
                this.agentField = value;
            }
        }
        
        /// <remarks/>
        public string TourCode {
            get {
                return this.tourCodeField;
            }
            set {
                this.tourCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string BaseFare {
            get {
                return this.baseFareField;
            }
            set {
                this.baseFareField = value;
            }
        }
        
        /// <remarks/>
        public string TotalTaxes {
            get {
                return this.totalTaxesField;
            }
            set {
                this.totalTaxesField = value;
            }
        }
        
        /// <remarks/>
        public string Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCodeBaseFare {
            get {
                return this.currencyCodeBaseFareField;
            }
            set {
                this.currencyCodeBaseFareField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCodeTotal {
            get {
                return this.currencyCodeTotalField;
            }
            set {
                this.currencyCodeTotalField = value;
            }
        }
        
        /// <remarks/>
        public string FareCalculation {
            get {
                return this.fareCalculationField;
            }
            set {
                this.fareCalculationField = value;
            }
        }
        
        /// <remarks/>
        public string EquivFare {
            get {
                return this.equivFareField;
            }
            set {
                this.equivFareField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCodeEquivFare {
            get {
                return this.currencyCodeEquivFareField;
            }
            set {
                this.currencyCodeEquivFareField = value;
            }
        }
        
        /// <remarks/>
        public bool PaymentForm {
            get {
                return this.paymentFormField;
            }
            set {
                this.paymentFormField = value;
            }
        }
        
        /// <remarks/>
        public string RFCAirline1 {
            get {
                return this.rFCAirline1Field;
            }
            set {
                this.rFCAirline1Field = value;
            }
        }
        
        /// <remarks/>
        public string PassengerNameCoupon {
            get {
                return this.passengerNameCouponField;
            }
            set {
                this.passengerNameCouponField = value;
            }
        }
        
        /// <remarks/>
        public string PNR {
            get {
                return this.pNRField;
            }
            set {
                this.pNRField = value;
            }
        }
        
        /// <remarks/>
        public string IATANumber {
            get {
                return this.iATANumberField;
            }
            set {
                this.iATANumberField = value;
            }
        }
        
        /// <remarks/>
        public string BaseFare1 {
            get {
                return this.baseFare1Field;
            }
            set {
                this.baseFare1Field = value;
            }
        }
        
        /// <remarks/>
        public string EquivFare1 {
            get {
                return this.equivFare1Field;
            }
            set {
                this.equivFare1Field = value;
            }
        }
        
        /// <remarks/>
        public string TotalFare {
            get {
                return this.totalFareField;
            }
            set {
                this.totalFareField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCard {
            get {
                return this.creditCardField;
            }
            set {
                this.creditCardField = value;
            }
        }
        
        /// <remarks/>
        public string APVL {
            get {
                return this.aPVLField;
            }
            set {
                this.aPVLField = value;
            }
        }
        
        /// <remarks/>
        public string FareCalculation1 {
            get {
                return this.fareCalculation1Field;
            }
            set {
                this.fareCalculation1Field = value;
            }
        }
        
        /// <remarks/>
        public string TicketMode {
            get {
                return this.ticketModeField;
            }
            set {
                this.ticketModeField = value;
            }
        }
        
        /// <remarks/>
        public string ConjunctiveTicketNumbers {
            get {
                return this.conjunctiveTicketNumbersField;
            }
            set {
                this.conjunctiveTicketNumbersField = value;
            }
        }
        
        /// <remarks/>
        public string Flight {
            get {
                return this.flightField;
            }
            set {
                this.flightField = value;
            }
        }
        
        /// <remarks/>
        public string TaxBreak {
            get {
                return this.taxBreakField;
            }
            set {
                this.taxBreakField = value;
            }
        }
        
        /// <remarks/>
        public bool TaxDown {
            get {
                return this.taxDownField;
            }
            set {
                this.taxDownField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InformationSegment {
        
        private string cuponNumberField;
        
        private string codeAirlineField;
        
        private string originField;
        
        private string destinationField;
        
        private string timeDepartureField;
        
        private string dateDepartureField;
        
        private string flightNumberField;
        
        private string resBookDesigCodeField;
        
        private string codeStatusField;
        
        private string fareBasisField;
        
        private string flightTypeField;
        
        /// <remarks/>
        public string cuponNumber {
            get {
                return this.cuponNumberField;
            }
            set {
                this.cuponNumberField = value;
            }
        }
        
        /// <remarks/>
        public string codeAirline {
            get {
                return this.codeAirlineField;
            }
            set {
                this.codeAirlineField = value;
            }
        }
        
        /// <remarks/>
        public string origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public string timeDeparture {
            get {
                return this.timeDepartureField;
            }
            set {
                this.timeDepartureField = value;
            }
        }
        
        /// <remarks/>
        public string dateDeparture {
            get {
                return this.dateDepartureField;
            }
            set {
                this.dateDepartureField = value;
            }
        }
        
        /// <remarks/>
        public string flightNumber {
            get {
                return this.flightNumberField;
            }
            set {
                this.flightNumberField = value;
            }
        }
        
        /// <remarks/>
        public string resBookDesigCode {
            get {
                return this.resBookDesigCodeField;
            }
            set {
                this.resBookDesigCodeField = value;
            }
        }
        
        /// <remarks/>
        public string codeStatus {
            get {
                return this.codeStatusField;
            }
            set {
                this.codeStatusField = value;
            }
        }
        
        /// <remarks/>
        public string fareBasis {
            get {
                return this.fareBasisField;
            }
            set {
                this.fareBasisField = value;
            }
        }
        
        /// <remarks/>
        public string flightType {
            get {
                return this.flightTypeField;
            }
            set {
                this.flightTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PhaseIV {
        
        private string bagsField;
        
        private string dateValidField;
        
        private string flightNumberField;
        
        private string originField;
        
        private string resBookDesigCodeField;
        
        private string dateFlightField;
        
        /// <remarks/>
        public string bags {
            get {
                return this.bagsField;
            }
            set {
                this.bagsField = value;
            }
        }
        
        /// <remarks/>
        public string dateValid {
            get {
                return this.dateValidField;
            }
            set {
                this.dateValidField = value;
            }
        }
        
        /// <remarks/>
        public string flightNumber {
            get {
                return this.flightNumberField;
            }
            set {
                this.flightNumberField = value;
            }
        }
        
        /// <remarks/>
        public string origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public string resBookDesigCode {
            get {
                return this.resBookDesigCodeField;
            }
            set {
                this.resBookDesigCodeField = value;
            }
        }
        
        /// <remarks/>
        public string dateFlight {
            get {
                return this.dateFlightField;
            }
            set {
                this.dateFlightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InformationPassenger {
        
        private string paxNumberField;
        
        private string paxNameField;
        
        private string paxTicketField;
        
        /// <remarks/>
        public string paxNumber {
            get {
                return this.paxNumberField;
            }
            set {
                this.paxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string paxName {
            get {
                return this.paxNameField;
            }
            set {
                this.paxNameField = value;
            }
        }
        
        /// <remarks/>
        public string paxTicket {
            get {
                return this.paxTicketField;
            }
            set {
                this.paxTicketField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InformationSeatsPassenger {
        
        private string paxNumberField;
        
        private string seatNumberField;
        
        /// <remarks/>
        public string paxNumber {
            get {
                return this.paxNumberField;
            }
            set {
                this.paxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string seatNumber {
            get {
                return this.seatNumberField;
            }
            set {
                this.seatNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InfoByItinerary {
        
        private string airlineRefField;
        
        private string marketingAirlineField;
        
        private string timeArrivalField;
        
        private string fligthNumberField;
        
        private string originField;
        
        private string destinationField;
        
        private string operatingAirlineField;
        
        private string departureTerminalField;
        
        private string arrivalTerminalField;
        
        private InformationSeatsPassenger[] seatsNumberField;
        
        /// <remarks/>
        public string airlineRef {
            get {
                return this.airlineRefField;
            }
            set {
                this.airlineRefField = value;
            }
        }
        
        /// <remarks/>
        public string marketingAirline {
            get {
                return this.marketingAirlineField;
            }
            set {
                this.marketingAirlineField = value;
            }
        }
        
        /// <remarks/>
        public string timeArrival {
            get {
                return this.timeArrivalField;
            }
            set {
                this.timeArrivalField = value;
            }
        }
        
        /// <remarks/>
        public string fligthNumber {
            get {
                return this.fligthNumberField;
            }
            set {
                this.fligthNumberField = value;
            }
        }
        
        /// <remarks/>
        public string origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public string operatingAirline {
            get {
                return this.operatingAirlineField;
            }
            set {
                this.operatingAirlineField = value;
            }
        }
        
        /// <remarks/>
        public string departureTerminal {
            get {
                return this.departureTerminalField;
            }
            set {
                this.departureTerminalField = value;
            }
        }
        
        /// <remarks/>
        public string arrivalTerminal {
            get {
                return this.arrivalTerminalField;
            }
            set {
                this.arrivalTerminalField = value;
            }
        }
        
        /// <remarks/>
        public InformationSeatsPassenger[] seatsNumber {
            get {
                return this.seatsNumberField;
            }
            set {
                this.seatsNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectTicketByPNR {
        
        private InfoByItinerary[] listItineraryInfoField;
        
        private InformationPassenger[] namePassengerListField;
        
        private PhaseIV[] phaseIVListField;
        
        private bool statusField;
        
        private string responseField;
        
        private string cCAirlinefeeField;
        
        private string cCAirlineField;
        
        private string pCCField;
        
        private string agentField;
        
        private string commissionField;
        
        private string customerIdentifierField;
        
        /// <remarks/>
        public InfoByItinerary[] listItineraryInfo {
            get {
                return this.listItineraryInfoField;
            }
            set {
                this.listItineraryInfoField = value;
            }
        }
        
        /// <remarks/>
        public InformationPassenger[] namePassengerList {
            get {
                return this.namePassengerListField;
            }
            set {
                this.namePassengerListField = value;
            }
        }
        
        /// <remarks/>
        public PhaseIV[] phaseIVList {
            get {
                return this.phaseIVListField;
            }
            set {
                this.phaseIVListField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public string CCAirlinefee {
            get {
                return this.cCAirlinefeeField;
            }
            set {
                this.cCAirlinefeeField = value;
            }
        }
        
        /// <remarks/>
        public string CCAirline {
            get {
                return this.cCAirlineField;
            }
            set {
                this.cCAirlineField = value;
            }
        }
        
        /// <remarks/>
        public string PCC {
            get {
                return this.pCCField;
            }
            set {
                this.pCCField = value;
            }
        }
        
        /// <remarks/>
        public string Agent {
            get {
                return this.agentField;
            }
            set {
                this.agentField = value;
            }
        }
        
        /// <remarks/>
        public string Commission {
            get {
                return this.commissionField;
            }
            set {
                this.commissionField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerIdentifier {
            get {
                return this.customerIdentifierField;
            }
            set {
                this.customerIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BuildPDFDocumentsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetInfoTicketByTicketNumberCompletedEventHandler(object sender, GetInfoTicketByTicketNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoTicketByTicketNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoTicketByTicketNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TicketInformationObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TicketInformationObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetInfoPassengerByTicketNumberCompletedEventHandler(object sender, GetInfoPassengerByTicketNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoPassengerByTicketNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoPassengerByTicketNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjectTicketByPNR Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjectTicketByPNR)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetInfoPassengerByPNRCompletedEventHandler(object sender, GetInfoPassengerByPNRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfoPassengerByPNRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfoPassengerByPNRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjectTicketByPNR Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjectTicketByPNR)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetTicketsByPNRCompletedEventHandler(object sender, GetTicketsByPNRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTicketsByPNRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTicketsByPNRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendPDFDocumentsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void EncryptCompletedEventHandler(object sender, EncryptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncryptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EncryptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DecryptCompletedEventHandler(object sender, DecryptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DecryptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DecryptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void WSTestCompletedEventHandler(object sender, WSTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WSTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WSTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591