//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.Presentation.Resources.Profiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.Presentation.Resources.Profiles.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveProfileFlow.
        /// </summary>
        internal static string ACTIVE_PROFILE_FLOW {
            get {
                return ResourceManager.GetString("ACTIVE_PROFILE_FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveProfiles.
        /// </summary>
        internal static string ACTIVE_PROFILES {
            get {
                return ResourceManager.GetString("ACTIVE_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string AST {
            get {
                return ResourceManager.GetString("AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‡.
        /// </summary>
        internal static string COMMAND_CROSS_LORAINE {
            get {
                return ResourceManager.GetString("COMMAND_CROSS_LORAINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DK.
        /// </summary>
        internal static string COMMAND_DK {
            get {
                return ResourceManager.GetString("COMMAND_DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5/.
        /// </summary>
        internal static string COMMAND_FIVE_SLASH {
            get {
                return ResourceManager.GetString("COMMAND_FIVE_SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string COMMAND_NINE {
            get {
                return ResourceManager.GetString("COMMAND_NINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE‡.
        /// </summary>
        internal static string COMMAND_PE_CROSS_LORAINE {
            get {
                return ResourceManager.GetString("COMMAND_PE_CROSS_LORAINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string COMMAND_X {
            get {
                return ResourceManager.GetString("COMMAND_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRMAS LA CREACIÓN DEL PERFIL.
        /// </summary>
        internal static string CREATE_PROFILE_CONFIRMATION {
            get {
                return ResourceManager.GetString("CREATE_PROFILE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿CONFIRMAS EL BORRADO DE LINEA?.
        /// </summary>
        internal static string DELETE_LINE {
            get {
                return ResourceManager.GetString("DELETE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL CORREO ELECTRÓNICO YA PERTENECE A OTRO PERFIL.
        /// </summary>
        internal static string EMAIL_EXIST {
            get {
                return ResourceManager.GetString("EMAIL_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string INDENT {
            get {
                return ResourceManager.GetString("INDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string INTEGRA_FIELD_ADDRESS {
            get {
                return ResourceManager.GetString("INTEGRA_FIELD_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute1.
        /// </summary>
        internal static string INTEGRA_FIELD_ATTRIBUTE1 {
            get {
                return ResourceManager.GetString("INTEGRA_FIELD_ATTRIBUTE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string INTEGRA_FIELD_CITY {
            get {
                return ResourceManager.GetString("INTEGRA_FIELD_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerName.
        /// </summary>
        internal static string INTEGRA_FIELD_CUSTOMER_NAME {
            get {
                return ResourceManager.GetString("INTEGRA_FIELD_CUSTOMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        internal static string INTEGRA_FIELD_MUNICIPALITY {
            get {
                return ResourceManager.GetString("INTEGRA_FIELD_MUNICIPALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalCode.
        /// </summary>
        internal static string INTEGRA_FIELD_POSTAL_CODE {
            get {
                return ResourceManager.GetString("INTEGRA_FIELD_POSTAL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC.
        /// </summary>
        internal static string INTEGRA_FIELD_RFC {
            get {
                return ResourceManager.GetString("INTEGRA_FIELD_RFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string INTEGRA_FIELD_STATE {
            get {
                return ResourceManager.GetString("INTEGRA_FIELD_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESA EL PASSWORD:.
        /// </summary>
        internal static string INTRODUCE_PASSWORD {
            get {
                return ResourceManager.GetString("INTRODUCE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD*.
        /// </summary>
        internal static string LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERFIL CREADO POR:.
        /// </summary>
        internal static string LABEL_PROFILE_CREATED_BY {
            get {
                return ResourceManager.GetString("LABEL_PROFILE_CREATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string LINE_TYPE_A {
            get {
                return ResourceManager.GetString("LINE_TYPE_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string LINE_TYPE_N {
            get {
                return ResourceManager.GetString("LINE_TYPE_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string LINE_TYPE_O {
            get {
                return ResourceManager.GetString("LINE_TYPE_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string LINE_TYPE_P {
            get {
                return ResourceManager.GetString("LINE_TYPE_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string LINE_TYPE_S {
            get {
                return ResourceManager.GetString("LINE_TYPE_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el tipo de linea adecuada:.
        /// </summary>
        internal static string MESSAGE_LINE_TYPE {
            get {
                return ResourceManager.GetString("MESSAGE_LINE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESO CONTRASEÑA PERFIL.
        /// </summary>
        internal static string MODAL_PWD_TITLE {
            get {
                return ResourceManager.GetString("MODAL_PWD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LA INFORMACIÓN NO PUEDE QUEDAR EN BLANCO.
        /// </summary>
        internal static string NO_EMPTY_INFORMATION {
            get {
                return ResourceManager.GetString("NO_EMPTY_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin coincidencias para:.
        /// </summary>
        internal static string NO_RESULTS_FOR {
            get {
                return ResourceManager.GetString("NO_RESULTS_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron coincidencias. Intente de nuevo.
        /// </summary>
        internal static string NO_RESULTS_TRY_AGAIN {
            get {
                return ResourceManager.GetString("NO_RESULTS_TRY_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LA LÍNEA CONTIENE CARACTERES NO VÁLIDOS.
        /// </summary>
        internal static string NO_VALID_CHARACTERS_IN_LINE {
            get {
                return ResourceManager.GetString("NO_VALID_CHARACTERS_IN_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributo 1.
        /// </summary>
        internal static string NODE_INTEGRA_TOOLTIP_TEXT_ATTRIBUTE1 {
            get {
                return ResourceManager.GetString("NODE_INTEGRA_TOOLTIP_TEXT_ATTRIBUTE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        internal static string NODE_INTEGRA_TOOLTIP_TEXT_CITY {
            get {
                return ResourceManager.GetString("NODE_INTEGRA_TOOLTIP_TEXT_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio.
        /// </summary>
        internal static string NODE_INTEGRA_TOOLTIP_TEXT_MUNICIPALITY {
            get {
                return ResourceManager.GetString("NODE_INTEGRA_TOOLTIP_TEXT_MUNICIPALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        internal static string NODE_INTEGRA_TOOLTIP_TEXT_POSTAL_CODE {
            get {
                return ResourceManager.GetString("NODE_INTEGRA_TOOLTIP_TEXT_POSTAL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC.
        /// </summary>
        internal static string NODE_INTEGRA_TOOLTIP_TEXT_RFC {
            get {
                return ResourceManager.GetString("NODE_INTEGRA_TOOLTIP_TEXT_RFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razon Social.
        /// </summary>
        internal static string NODE_INTEGRA_TOOLTIP_TEXT_SOCIAL_REASON {
            get {
                return ResourceManager.GetString("NODE_INTEGRA_TOOLTIP_TEXT_SOCIAL_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string NODE_INTEGRA_TOOLTIP_TEXT_STATE {
            get {
                return ResourceManager.GetString("NODE_INTEGRA_TOOLTIP_TEXT_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle, Número y Colonia.
        /// </summary>
        internal static string NODE_INTEGRA_TOOLTIP_TEXT_STREET_AND_NUMBER {
            get {
                return ResourceManager.GetString("NODE_INTEGRA_TOOLTIP_TEXT_STREET_AND_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoData.
        /// </summary>
        internal static string NODE_NO_DATA_NAME {
            get {
                return ResourceManager.GetString("NODE_NO_DATA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Información del Perfil.
        /// </summary>
        internal static string NODE_NO_DATA_TEXT {
            get {
                return ResourceManager.GetString("NODE_NO_DATA_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona las Líneas Opcionales que Desees Ingresa a la Reservación.
        /// </summary>
        internal static string NODE_OPTIONAL_TOOLTIP_TEXT {
            get {
                return ResourceManager.GetString("NODE_OPTIONAL_TOOLTIP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string NODE_PROFILES_NAME {
            get {
                return ResourceManager.GetString("NODE_PROFILES_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATOS DEL PERFIL.
        /// </summary>
        internal static string NODE_PROFILES_TEXT {
            get {
                return ResourceManager.GetString("NODE_PROFILES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star1Integra.
        /// </summary>
        internal static string NODE_STAR1_INTEGRA {
            get {
                return ResourceManager.GetString("NODE_STAR1_INTEGRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star1.
        /// </summary>
        internal static string NODE_STAR1_NAME {
            get {
                return ResourceManager.GetString("NODE_STAR1_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPRESA.
        /// </summary>
        internal static string NODE_STAR1_TEXT {
            get {
                return ResourceManager.GetString("NODE_STAR1_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MYCTS.
        /// </summary>
        internal static string NODE_STAR1_TEXT2 {
            get {
                return ResourceManager.GetString("NODE_STAR1_TEXT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star2.
        /// </summary>
        internal static string NODE_STAR2_NAME {
            get {
                return ResourceManager.GetString("NODE_STAR2_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASAJERO.
        /// </summary>
        internal static string NODE_STAR2_TEXT {
            get {
                return ResourceManager.GetString("NODE_STAR2_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to star2Info.
        /// </summary>
        internal static string NODE_STAR2INFO_NAME {
            get {
                return ResourceManager.GetString("NODE_STAR2INFO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to star2List.
        /// </summary>
        internal static string NODE_STAR2LIST_NAME {
            get {
                return ResourceManager.GetString("NODE_STAR2LIST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTRELLAS DE 2DO NIVEL.
        /// </summary>
        internal static string NODE_STAR2LIST_TEXT {
            get {
                return ResourceManager.GetString("NODE_STAR2LIST_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presiona el Boton Derecho del Mouse para Desplegar mas Opciones.
        /// </summary>
        internal static string NODE_TOOLTIP_TEXT {
            get {
                return ResourceManager.GetString("NODE_TOOLTIP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA MAYOR COMODIDAD EL NOMBRE DEL PERFIL AHORA SERA EL DK..
        /// </summary>
        internal static string NOMBRE_DK {
            get {
                return ResourceManager.GetString("NOMBRE_DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRASEÑA INCORRECTA.
        /// </summary>
        internal static string PASSWORD_ERROR {
            get {
                return ResourceManager.GetString("PASSWORD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORD*.
        /// </summary>
        internal static string PWD_ID {
            get {
                return ResourceManager.GetString("PWD_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿DESEAS GUARDAR LOS CAMBIOS?.
        /// </summary>
        internal static string SAVE_CHANGES {
            get {
                return ResourceManager.GetString("SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string STAR_LEVEL_ONE {
            get {
                return ResourceManager.GetString("STAR_LEVEL_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string STAR_LEVEL_TWO {
            get {
                return ResourceManager.GetString("STAR_LEVEL_TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucAddProfileInfo.
        /// </summary>
        internal static string UC_ADD_PROFILE_INFO {
            get {
                return ResourceManager.GetString("UC_ADD_PROFILE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucCreateProfileFirstLevel.
        /// </summary>
        internal static string UC_CREATE_PROFILE_FIRST_LEVEL {
            get {
                return ResourceManager.GetString("UC_CREATE_PROFILE_FIRST_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucCreateProfileSecondLevel.
        /// </summary>
        internal static string UC_CREATE_PROFILE_SECOND_LEVEL {
            get {
                return ResourceManager.GetString("UC_CREATE_PROFILE_SECOND_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.Profiles.ucFirstLevelProfiles.
        /// </summary>
        internal static string UC_FIRST_LEVEL_PROFILES {
            get {
                return ResourceManager.GetString("UC_FIRST_LEVEL_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucProfileInfoDisplay.
        /// </summary>
        internal static string UC_PROFILE_INFO_DISPLAY {
            get {
                return ResourceManager.GetString("UC_PROFILE_INFO_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucProfileSecondLevelContinue.
        /// </summary>
        internal static string UC_PROFILE_SECOND_LEVEL_CONTINUE {
            get {
                return ResourceManager.GetString("UC_PROFILE_SECOND_LEVEL_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucRenameProfile.
        /// </summary>
        internal static string UC_RENAME_PROFILE {
            get {
                return ResourceManager.GetString("UC_RENAME_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucSearchProfileDetailed.
        /// </summary>
        internal static string UC_SEARCH_PROFILE_DETAILED {
            get {
                return ResourceManager.GetString("UC_SEARCH_PROFILE_DETAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.Profiles.UcSecondLevelProfiles.
        /// </summary>
        internal static string UC_SECOND_LEVEL_PROFILES {
            get {
                return ResourceManager.GetString("UC_SECOND_LEVEL_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucWelcomeProfiles.
        /// </summary>
        internal static string UC_WELCOME_PROFILES {
            get {
                return ResourceManager.GetString("UC_WELCOME_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMFIRMAS LA ACTUALIZACION DEL PERFIL.
        /// </summary>
        internal static string UPDATE_PROFILE_CONFIRMATION {
            get {
                return ResourceManager.GetString("UPDATE_PROFILE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRMAR LA ACTUALIZACION DEL PERFIL  {0}  CON EL NOMBRE DEL DK  {1}
        ///
        ///TODOS LOS PERFILES QUE COINCIDAN CON EL DK DE ESTE PERFIL SERÁN ALMACENADOS EN LA PESTAÑA DE INFORMACIÓN HISTÓRICA..
        /// </summary>
        internal static string UPDATE_PROFILE_CONFIRMATION_FIRST_LEVEL {
            get {
                return ResourceManager.GetString("UPDATE_PROFILE_CONFIRMATION_FIRST_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMFIRMAS LA ACTUALIZACION DEL PERFIL.
        /// </summary>
        internal static string UPDATE_PROFILE_CONFIRMATION_SECOND_LEVEL {
            get {
                return ResourceManager.GetString("UPDATE_PROFILE_CONFIRMATION_SECOND_LEVEL", resourceCulture);
            }
        }
    }
}
