//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.Presentation.Resources.Profiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Profiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.Presentation.Resources.Profiles.Profiles", typeof(Profiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL CAMPO COLONIA NO HA SIDO INGRESADO.
        /// </summary>
        internal static string CAMPO_COLONIA_NO_INGRESADO {
            get {
                return ResourceManager.GetString("CAMPO_COLONIA_NO_INGRESADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL APELLIDO.
        /// </summary>
        internal static string DEBES_INGRESAR_APELLIDO {
            get {
                return ResourceManager.GetString("DEBES_INGRESAR_APELLIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL NOMBRE.
        /// </summary>
        internal static string DEBES_INGRESAR_NOMBRE {
            get {
                return ResourceManager.GetString("DEBES_INGRESAR_NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL NÚMERO TELEFÓNICO DE LA EMPRESA.
        /// </summary>
        internal static string DEBES_INGRESAR_NUMERO_TELEFONICO {
            get {
                return ResourceManager.GetString("DEBES_INGRESAR_NUMERO_TELEFONICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL PCC.
        /// </summary>
        internal static string DEBES_INGRESAR_PCC {
            get {
                return ResourceManager.GetString("DEBES_INGRESAR_PCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LA DIRECCION DE EMAIL NO ESTA EN UN FORMATO VALIDO.
        /// </summary>
        internal static string DIRECCION_EMAIL_NO_VALIDA {
            get {
                return ResourceManager.GetString("DIRECCION_EMAIL_NO_VALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL FORMATO DE CORREO ELECTRÓNICO ES INCORRECTO.
        /// </summary>
        internal static string FORMATO_CORREO_ELECT_INCORRECTO {
            get {
                return ResourceManager.GetString("FORMATO_CORREO_ELECT_INCORRECTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR AEREOLINEA, NUMERO VIAJERO FRECUENTE Y NOMBRE.
        /// </summary>
        internal static string INGRESA_AEROLINEA_FF_NOMBRE {
            get {
                return ResourceManager.GetString("INGRESA_AEROLINEA_FF_NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL AÑO DE NACIMIENTO DEL PASAJERO.
        /// </summary>
        internal static string INGRESA_ANIO_NACIMIENTO {
            get {
                return ResourceManager.GetString("INGRESA_ANIO_NACIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL CAMPO CALLE NO HA SIDO INGRESADO.
        /// </summary>
        internal static string INGRESA_CAMPO_CALLE {
            get {
                return ResourceManager.GetString("INGRESA_CAMPO_CALLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL CAMPO CIUDAD NO HA SIDO INGRESADO.
        /// </summary>
        internal static string INGRESA_CAMPO_CIUDAD {
            get {
                return ResourceManager.GetString("INGRESA_CAMPO_CIUDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR DATOS EN EL CAMPO CREADO POR.
        /// </summary>
        internal static string INGRESA_CAMPO_CREADO_POR {
            get {
                return ResourceManager.GetString("INGRESA_CAMPO_CREADO_POR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL CAMPO ESTADO NO HA SIDO INGRESADO.
        /// </summary>
        internal static string INGRESA_CAMPO_ESTADO {
            get {
                return ResourceManager.GetString("INGRESA_CAMPO_ESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR TODOS LOS CAMPOS DE LA DIRECCIÓN PERSONAL.
        /// </summary>
        internal static string INGRESA_CAMPOS_DIRECCION_PERSONAL {
            get {
                return ResourceManager.GetString("INGRESA_CAMPOS_DIRECCION_PERSONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESA EL CÓDIGO LOCATION O DK DE LA EMPRESA.
        /// </summary>
        internal static string INGRESA_COD_LOCATION_EMPRESA {
            get {
                return ResourceManager.GetString("INGRESA_COD_LOCATION_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR CÓDIGO Y NÚMERO DE ARRENDADORA.
        /// </summary>
        internal static string INGRESA_CODIGO_ARRENDADORA {
            get {
                return ResourceManager.GetString("INGRESA_CODIGO_ARRENDADORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR CÓDIGO Y NÚMERO DE HOTEL.
        /// </summary>
        internal static string INGRESA_CODIGO_HOTEL {
            get {
                return ResourceManager.GetString("INGRESA_CODIGO_HOTEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR CÓDIGO, NÚMERO, VIGENCIA Y APELLIDO DE LA TARJETA DE CREDITO DEL CLIENTE.
        /// </summary>
        internal static string INGRESA_DATOS_TARJETA_CLIENTE {
            get {
                return ResourceManager.GetString("INGRESA_DATOS_TARJETA_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR CÓDIGO, NÚMERO Y VIGENCIA DE LA TARJETA DE CREDITO.
        /// </summary>
        internal static string INGRESA_DATOS_TARJETA_CREDITO {
            get {
                return ResourceManager.GetString("INGRESA_DATOS_TARJETA_CREDITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR CÓDIGO, NÚMERO Y VIGENCIA DE LA TARJETA DE CREDITO DEL CLIENTE.
        /// </summary>
        internal static string INGRESA_DATOS_TARJETA_CREDITO_CLIENTE {
            get {
                return ResourceManager.GetString("INGRESA_DATOS_TARJETA_CREDITO_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESA DELEGACIÓN O MUNICIPIO.
        /// </summary>
        internal static string INGRESA_DEL_O_MUNICIPIO {
            get {
                return ResourceManager.GetString("INGRESA_DEL_O_MUNICIPIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL DIA DE NACIMIENTO DEL PASAJERO.
        /// </summary>
        internal static string INGRESA_DIA_NACIMIENTO {
            get {
                return ResourceManager.GetString("INGRESA_DIA_NACIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL EMAIL DEL CONTACTO.
        /// </summary>
        internal static string INGRESA_EMAIL_CONTACTO {
            get {
                return ResourceManager.GetString("INGRESA_EMAIL_CONTACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL EMAIL DEL PASAJERO.
        /// </summary>
        internal static string INGRESA_EMAIL_PASAJERO {
            get {
                return ResourceManager.GetString("INGRESA_EMAIL_PASAJERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESA DIA, MES Y AÑO DE LA FECHA DE NACIMIENTO.
        /// </summary>
        internal static string INGRESA_FECHA_NACIMIENTO {
            get {
                return ResourceManager.GetString("INGRESA_FECHA_NACIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESA FECHA DE VIGENCIA DEL NÚMERO DE PASAPORTE.
        /// </summary>
        internal static string INGRESA_FECHA_VIGENCIA_PASAPORTE {
            get {
                return ResourceManager.GetString("INGRESA_FECHA_VIGENCIA_PASAPORTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESA FECHA DE VIGENCIA DEL NÚMERO DE VISA.
        /// </summary>
        internal static string INGRESA_FECHA_VIGENCIA_VISA {
            get {
                return ResourceManager.GetString("INGRESA_FECHA_VIGENCIA_VISA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL MES DE NACIMIENTO DEL PASAJERO.
        /// </summary>
        internal static string INGRESA_MES_NACIMIENTO {
            get {
                return ResourceManager.GetString("INGRESA_MES_NACIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR POR LO MENOS NOMBRE Y APELLIDO PATERNO.
        /// </summary>
        internal static string INGRESA_MINIMO_NOMBRE_APELLIDO {
            get {
                return ResourceManager.GetString("INGRESA_MINIMO_NOMBRE_APELLIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL NOMBRE DEL CONTACTO EN LA EMPRESA.
        /// </summary>
        internal static string INGRESA_NOMBRE_CONTACTO {
            get {
                return ResourceManager.GetString("INGRESA_NOMBRE_CONTACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL NOMBRE DE LA EMPRESA.
        /// </summary>
        internal static string INGRESA_NOMBRE_EMPRESA {
            get {
                return ResourceManager.GetString("INGRESA_NOMBRE_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESA EL NOMBRE DEL PERFIL.
        /// </summary>
        internal static string INGRESA_NOMBRE_PERFIL {
            get {
                return ResourceManager.GetString("INGRESA_NOMBRE_PERFIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESA EL NOMBRE DEL PERFIL DE PRIMER NIVEL.
        /// </summary>
        internal static string INGRESA_NOMBRE_PERFIL_1ER_NIVEL {
            get {
                return ResourceManager.GetString("INGRESA_NOMBRE_PERFIL_1ER_NIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESA EL NOMBRE DEL PERFIL DEL EMPLEADO.
        /// </summary>
        internal static string INGRESA_NOMBRE_PERFIL_2DO_NIVEL {
            get {
                return ResourceManager.GetString("INGRESA_NOMBRE_PERFIL_2DO_NIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESAR EL NUEVO NOMBRE DEL PERFIL DE PRIMER NIVEL.
        /// </summary>
        internal static string INGRESA_NUEVO_NOMBRE_PRIMER_NIVEL {
            get {
                return ResourceManager.GetString("INGRESA_NUEVO_NOMBRE_PRIMER_NIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESAR EL NUEVO NOMBRE DEL PERFIL DE SEGUNDO NIVEL.
        /// </summary>
        internal static string INGRESA_NUEVO_NOMBRE_SEGUNDO_NIVEL {
            get {
                return ResourceManager.GetString("INGRESA_NUEVO_NOMBRE_SEGUNDO_NIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES DE INGRESAR EL PASSWORD.
        /// </summary>
        internal static string INGRESA_PASSWORD {
            get {
                return ResourceManager.GetString("INGRESA_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESA LA RAZON SOCIAL.
        /// </summary>
        internal static string INGRESA_RAZON_SOCIAL {
            get {
                return ResourceManager.GetString("INGRESA_RAZON_SOCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INGRESA RFC CON TODOS SUS CAMPOS.
        /// </summary>
        internal static string INGRESA_RFC_COMPLETO {
            get {
                return ResourceManager.GetString("INGRESA_RFC_COMPLETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL NÚMERO TELEFÓNICO DE LA EMPRESA.
        /// </summary>
        internal static string INGRESA_TELEFONO_EMPRESA {
            get {
                return ResourceManager.GetString("INGRESA_TELEFONO_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBES INGRESAR EL TIPO DE TELÉFONO.
        /// </summary>
        internal static string INGRESA_TIPO_TELEFONO {
            get {
                return ResourceManager.GetString("INGRESA_TIPO_TELEFONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL NOMBRE DE PERFIL YA EXISTE.
        /// </summary>
        internal static string NOMBRE_PERFIL_EXISTENTE {
            get {
                return ResourceManager.GetString("NOMBRE_PERFIL_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL NOMBRE DEL PERFIL DEL EMPLEADO DEBE TENER UNA DIAGONAL INTERMEDIA.
        /// </summary>
        internal static string PERFIL_EMPLEADO_DEBE_CONTENER_DIAGONAL {
            get {
                return ResourceManager.GetString("PERFIL_EMPLEADO_DEBE_CONTENER_DIAGONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL NOMBRE DEL PERFIL DEL EMPLEADO YA EXISTE.
        /// </summary>
        internal static string PERFIL_EMPLEADO_EXISTENTE {
            get {
                return ResourceManager.GetString("PERFIL_EMPLEADO_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPORCIONA EL CÓDIGO POSTAL.
        /// </summary>
        internal static string PROPORCIONA_CODIGO_POSTAL {
            get {
                return ResourceManager.GetString("PROPORCIONA_CODIGO_POSTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPORCIONA EL DATO QUE DESEAS INGRESAR AL PERFIL.
        /// </summary>
        internal static string PROPORCIONA_DATO_A_INGRESAR_PERFIL {
            get {
                return ResourceManager.GetString("PROPORCIONA_DATO_A_INGRESAR_PERFIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPORCIONA EL NÚMERO EXTERIOR.
        /// </summary>
        internal static string PROPORCIONA_NUMERO_EXT {
            get {
                return ResourceManager.GetString("PROPORCIONA_NUMERO_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECCIONA EL TIPO DE LÍNEA A INGRESAR.
        /// </summary>
        internal static string SELECCIONA_TIPO_LINEA {
            get {
                return ResourceManager.GetString("SELECCIONA_TIPO_LINEA", resourceCulture);
            }
        }
    }
}
