CREATE TABLE [dbo].[CTS_CLIENTES_V] (
    [CUSTOMER_NUMBER] NVARCHAR (255) NULL,
    [ATTRIBUTE1]      NVARCHAR (255) NULL,
    [SALESREP_NUMBER] NVARCHAR (255) NULL,
    [SALESREP_ID]     FLOAT (53)     NULL,
    [CUSTOMER_NAME]   NVARCHAR (255) NULL,
    [RFC]             NVARCHAR (255) NULL,
    [ATTRIBUTE2]      NVARCHAR (255) NULL,
    [CUSTOMER_ID]     FLOAT (53)     NULL,
    [SITE_USE_ID]     FLOAT (53)     NULL,
    [PARTY_SITE_ID]   FLOAT (53)     NULL,
    [PARTY_ID]        FLOAT (53)     NULL,
    [LOCATION]        NVARCHAR (255) NULL,
    [STATUS]          NVARCHAR (255) NULL,
    [STATUS_SITE]     NVARCHAR (255) NULL,
    [CCI]             NVARCHAR (255) NULL,
    [ATTRIBUTE5]      NVARCHAR (255) NULL,
    [ORG_ID]          FLOAT (53)     NULL,
    [DIRECCION]       NVARCHAR (255) NULL,
    [CONTACTO]        NVARCHAR (255) NULL
);

