CREATE TABLE [dbo].[CTS_PROVEEDORES_V] (
    [ID_PROVEEDOR]            NVARCHAR (255) NULL,
    [VENDOR_TYPE_LOOKUP_CODE] NVARCHAR (255) NULL,
    [VENDOR_NAME]             NVARCHAR (255) NULL,
    [VENDOR_SITE_CODE]        NVARCHAR (255) NULL,
    [VENDOR_ID]               FLOAT (53)     NULL,
    [VENDOR_SITE_ID]          FLOAT (53)     NULL,
    [ATTRIBUTE3]              NVARCHAR (255) NULL,
    [ORG_ID]                  FLOAT (53)     NULL,
    [GLOBAL_ATTRIBUTE1]       NVARCHAR (255) NULL,
    [GLOBAL_ATTRIBUTE2]       NVARCHAR (255) NULL,
    [GLOBAL_ATTRIBUTE3]       NVARCHAR (255) NULL,
    [GLOBAL_ATTRIBUTE4]       NVARCHAR (255) NULL,
    [GLOBAL_ATTRIBUTE5]       NVARCHAR (255) NULL,
    [GLOBAL_ATTRIBUTE6]       NVARCHAR (255) NULL,
    [GLOBAL_ATTRIBUTE7]       NVARCHAR (255) NULL,
    [GLOBAL_ATTRIBUTE8]       NVARCHAR (255) NULL,
    [GLOBAL_ATTRIBUTE9]       NVARCHAR (255) NULL
);

