CREATE TABLE [dbo].[DetailsPNRHotel] (
    [ID]                  INT            IDENTITY (1, 1) NOT NULL,
    [Record]              VARCHAR (50)   NULL,
    [Confirmation_Number] VARCHAR (50)   NULL,
    [Hotel]               VARCHAR (50)   NULL,
    [Provid_Direc_Pay]    BIT            NULL,
    [DK]                  VARCHAR (50)   NULL,
    [Phone]               VARCHAR (50)   NULL,
    [RFC]                 VARCHAR (50)   NULL,
    [Mail]                VARCHAR (50)   NULL,
    [Request]             VARCHAR (50)   NULL,
    [Payment_form]        VARCHAR (50)   NULL,
    [Car_Number]          INT            NULL,
    [Sales_Source]        VARCHAR (50)   NULL,
    [Operational_Unit]    VARCHAR (50)   NULL,
    [User]                VARCHAR (50)   NULL,
    [Service_Type]        VARCHAR (50)   NULL,
    [Provider]            VARCHAR (50)   NULL,
    [Site]                VARCHAR (50)   NULL,
    [In_Date]             DATETIME       CONSTRAINT [DF_DetailsPNRHotel_In_Date] DEFAULT (getdate()) NULL,
    [Out_Date]            DATETIME       CONSTRAINT [DF_DetailsPNRHotel_Out_Date] DEFAULT (getdate()) NULL,
    [City]                VARCHAR (50)   NULL,
    [Room]                VARCHAR (50)   NULL,
    [Room_Type]           VARCHAR (50)   NULL,
    [Meal_Plan]           VARCHAR (50)   NULL,
    [Number_Nights]       FLOAT (53)     NULL,
    [Passenger_Name]      VARCHAR (50)   NULL,
    [Passenger_Number]    INT            NULL,
    [Surname]             VARCHAR (50)   NULL,
    [Title]               VARCHAR (50)   NULL,
    [Passenger_Type]      VARCHAR (50)   NULL,
    [Rate]                VARCHAR (50)   NULL,
    [Currency]            VARCHAR (10)   NULL,
    [Provider_Commission] FLOAT (53)     NULL,
    [Cost]                FLOAT (53)     NULL,
    [Price]               FLOAT (53)     NULL,
    [Taxes]               FLOAT (53)     NULL,
    [Created_Date]        DATETIME       CONSTRAINT [DF_dbo.OperationHotels_C_Date] DEFAULT (getdate()) NULL,
    [Time_Limit]          DATETIME       CONSTRAINT [DF_DetailsPNRHotel_Time_Limit] DEFAULT (getdate()) NULL,
    [Status]              VARCHAR (50)   NULL,
    [Cancel_Number]       VARCHAR (50)   NULL,
    [ChainCode]           VARCHAR (50)   NULL,
    [ChangeType]          FLOAT (53)     NULL,
    [OrgId]               INT            NULL,
    [Pcc]                 VARCHAR (10)   NULL,
    [RemarksString]       VARCHAR (3000) NULL,
    [UserName]            VARCHAR (50)   NULL,
    [GeaErrorMsg]         VARCHAR (MAX)  NULL,
    [Description]         VARCHAR (MAX)  NULL,
    [In_City]             VARCHAR (50)   NULL,
    [Out_City]            VARCHAR (50)   NULL
);

