CREATE TABLE [dbo].[ToolOnlineRulesDelete] (
    [Corporative]  VARCHAR (50) NULL,
    [ToolOnline]   VARCHAR (30) NULL,
    [Attribute1]   VARCHAR (6)  NULL,
    [Supervisor]   VARCHAR (50) NULL,
    [SupAgent]     INT          NULL,
    [SupPCC]       VARCHAR (50) NULL,
    [SupStatus]    CHAR (20)    NULL,
    [Consultor1]   VARCHAR (50) NULL,
    [ConAgent1]    INT          NULL,
    [ConPCC1]      VARCHAR (50) NULL,
    [ConStatus1]   CHAR (20)    NULL,
    [CountConsul1] BIT          NULL,
    [Consultor2]   VARCHAR (50) NULL,
    [ConAgent2]    INT          NULL,
    [ConPCC2]      VARCHAR (50) NULL,
    [ConStatus2]   CHAR (20)    NULL,
    [CountConsul2] BIT          NULL,
    [Consultor3]   VARCHAR (50) NULL,
    [ConAgent3]    INT          NULL,
    [ConPCC3]      VARCHAR (50) NULL,
    [ConStatus3]   CHAR (20)    NULL,
    [CountConsul3] BIT          NULL,
    [Consultor4]   VARCHAR (50) NULL,
    [ConAgent4]    INT          NULL,
    [ConPCC4]      VARCHAR (50) NULL,
    [ConStatus4]   CHAR (20)    NULL,
    [CountConsul4] BIT          NULL,
    [Consultor5]   VARCHAR (50) NULL,
    [ConAgent5]    INT          NULL,
    [ConPCC5]      VARCHAR (50) NULL,
    [ConStatus5]   CHAR (20)    NULL,
    [CountConsul5] BIT          NULL,
    [FechaInsert]  DATETIME     NULL,
    [InsertBy]     INT          NULL,
    [FechaUpdate]  DATETIME     NULL,
    [UpdateBy]     INT          NULL,
    [FechaDelete]  DATETIME     NULL,
    [DeleteBy]     INT          NULL
);

