//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ALAgreementsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ALAgreementsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.ALAgreementsResources", typeof(ALAgreementsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DomesticComission.
        /// </summary>
        internal static string PARAM_DOMESTICCOMISSION {
            get {
                return ResourceManager.GetString("PARAM_DOMESTICCOMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDAlCode.
        /// </summary>
        internal static string PARAM_IDAlCODE {
            get {
                return ResourceManager.GetString("PARAM_IDAlCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternationalComission.
        /// </summary>
        internal static string PARAM_INTERCOMISSION {
            get {
                return ResourceManager.GetString("PARAM_INTERCOMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSI.
        /// </summary>
        internal static string PARAM_OSI {
            get {
                return ResourceManager.GetString("PARAM_OSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlCodeToSearch.
        /// </summary>
        internal static string PARAM_QUERY {
            get {
                return ResourceManager.GetString("PARAM_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TourCode.
        /// </summary>
        internal static string PARAM_TOURCODE {
            get {
                return ResourceManager.GetString("PARAM_TOURCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetALAgreements.
        /// </summary>
        internal static string SP_GetALAgreements {
            get {
                return ResourceManager.GetString("SP_GetALAgreements", resourceCulture);
            }
        }
    }
}
