//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3082
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CatValuesXMLQuealityControlsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatValuesXMLQuealityControlsResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.CatValuesXMLQuealityControlsResources", typeof(CatValuesXMLQuealityControlsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C1.
        /// </summary>
        internal static string PARAM_C1 {
            get {
                return ResourceManager.GetString("PARAM_C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C10.
        /// </summary>
        internal static string PARAM_C10 {
            get {
                return ResourceManager.GetString("PARAM_C10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C11.
        /// </summary>
        internal static string PARAM_C11 {
            get {
                return ResourceManager.GetString("PARAM_C11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C12.
        /// </summary>
        internal static string PARAM_C12 {
            get {
                return ResourceManager.GetString("PARAM_C12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C13.
        /// </summary>
        internal static string PARAM_C13 {
            get {
                return ResourceManager.GetString("PARAM_C13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C14.
        /// </summary>
        internal static string PARAM_C14 {
            get {
                return ResourceManager.GetString("PARAM_C14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C15.
        /// </summary>
        internal static string PARAM_C15 {
            get {
                return ResourceManager.GetString("PARAM_C15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C16.
        /// </summary>
        internal static string PARAM_C16 {
            get {
                return ResourceManager.GetString("PARAM_C16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C17.
        /// </summary>
        internal static string PARAM_C17 {
            get {
                return ResourceManager.GetString("PARAM_C17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C18.
        /// </summary>
        internal static string PARAM_C18 {
            get {
                return ResourceManager.GetString("PARAM_C18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C19.
        /// </summary>
        internal static string PARAM_C19 {
            get {
                return ResourceManager.GetString("PARAM_C19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C2.
        /// </summary>
        internal static string PARAM_C2 {
            get {
                return ResourceManager.GetString("PARAM_C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C20.
        /// </summary>
        internal static string PARAM_C20 {
            get {
                return ResourceManager.GetString("PARAM_C20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C21.
        /// </summary>
        internal static string PARAM_C21 {
            get {
                return ResourceManager.GetString("PARAM_C21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C22.
        /// </summary>
        internal static string PARAM_C22 {
            get {
                return ResourceManager.GetString("PARAM_C22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C23.
        /// </summary>
        internal static string PARAM_C23 {
            get {
                return ResourceManager.GetString("PARAM_C23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C24.
        /// </summary>
        internal static string PARAM_C24 {
            get {
                return ResourceManager.GetString("PARAM_C24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C25.
        /// </summary>
        internal static string PARAM_C25 {
            get {
                return ResourceManager.GetString("PARAM_C25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C26.
        /// </summary>
        internal static string PARAM_C26 {
            get {
                return ResourceManager.GetString("PARAM_C26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C27.
        /// </summary>
        internal static string PARAM_C27 {
            get {
                return ResourceManager.GetString("PARAM_C27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C29.
        /// </summary>
        internal static string PARAM_C29 {
            get {
                return ResourceManager.GetString("PARAM_C29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C3.
        /// </summary>
        internal static string PARAM_C3 {
            get {
                return ResourceManager.GetString("PARAM_C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C30.
        /// </summary>
        internal static string PARAM_C30 {
            get {
                return ResourceManager.GetString("PARAM_C30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C4.
        /// </summary>
        internal static string PARAM_C4 {
            get {
                return ResourceManager.GetString("PARAM_C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C5.
        /// </summary>
        internal static string PARAM_C5 {
            get {
                return ResourceManager.GetString("PARAM_C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C6.
        /// </summary>
        internal static string PARAM_C6 {
            get {
                return ResourceManager.GetString("PARAM_C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C7.
        /// </summary>
        internal static string PARAM_C7 {
            get {
                return ResourceManager.GetString("PARAM_C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C8.
        /// </summary>
        internal static string PARAM_C8 {
            get {
                return ResourceManager.GetString("PARAM_C8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C9.
        /// </summary>
        internal static string PARAM_C9 {
            get {
                return ResourceManager.GetString("PARAM_C9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DKToSearch.
        /// </summary>
        internal static string PARAM_QUERY {
            get {
                return ResourceManager.GetString("PARAM_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C9.
        /// </summary>
        internal static string PARAM_QUERY10 {
            get {
                return ResourceManager.GetString("PARAM_QUERY10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C10.
        /// </summary>
        internal static string PARAM_QUERY11 {
            get {
                return ResourceManager.GetString("PARAM_QUERY11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C11.
        /// </summary>
        internal static string PARAM_QUERY12 {
            get {
                return ResourceManager.GetString("PARAM_QUERY12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C12.
        /// </summary>
        internal static string PARAM_QUERY13 {
            get {
                return ResourceManager.GetString("PARAM_QUERY13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C13.
        /// </summary>
        internal static string PARAM_QUERY14 {
            get {
                return ResourceManager.GetString("PARAM_QUERY14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C14.
        /// </summary>
        internal static string PARAM_QUERY15 {
            get {
                return ResourceManager.GetString("PARAM_QUERY15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C15.
        /// </summary>
        internal static string PARAM_QUERY16 {
            get {
                return ResourceManager.GetString("PARAM_QUERY16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C16.
        /// </summary>
        internal static string PARAM_QUERY17 {
            get {
                return ResourceManager.GetString("PARAM_QUERY17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C17.
        /// </summary>
        internal static string PARAM_QUERY18 {
            get {
                return ResourceManager.GetString("PARAM_QUERY18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C18.
        /// </summary>
        internal static string PARAM_QUERY19 {
            get {
                return ResourceManager.GetString("PARAM_QUERY19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C1.
        /// </summary>
        internal static string PARAM_QUERY2 {
            get {
                return ResourceManager.GetString("PARAM_QUERY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C19.
        /// </summary>
        internal static string PARAM_QUERY20 {
            get {
                return ResourceManager.GetString("PARAM_QUERY20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C20.
        /// </summary>
        internal static string PARAM_QUERY21 {
            get {
                return ResourceManager.GetString("PARAM_QUERY21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C21.
        /// </summary>
        internal static string PARAM_QUERY22 {
            get {
                return ResourceManager.GetString("PARAM_QUERY22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C22.
        /// </summary>
        internal static string PARAM_QUERY23 {
            get {
                return ResourceManager.GetString("PARAM_QUERY23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C23.
        /// </summary>
        internal static string PARAM_QUERY24 {
            get {
                return ResourceManager.GetString("PARAM_QUERY24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C24.
        /// </summary>
        internal static string PARAM_QUERY25 {
            get {
                return ResourceManager.GetString("PARAM_QUERY25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C25.
        /// </summary>
        internal static string PARAM_QUERY26 {
            get {
                return ResourceManager.GetString("PARAM_QUERY26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C26.
        /// </summary>
        internal static string PARAM_QUERY27 {
            get {
                return ResourceManager.GetString("PARAM_QUERY27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C27.
        /// </summary>
        internal static string PARAM_QUERY28 {
            get {
                return ResourceManager.GetString("PARAM_QUERY28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C28.
        /// </summary>
        internal static string PARAM_QUERY29 {
            get {
                return ResourceManager.GetString("PARAM_QUERY29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C2.
        /// </summary>
        internal static string PARAM_QUERY3 {
            get {
                return ResourceManager.GetString("PARAM_QUERY3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C29.
        /// </summary>
        internal static string PARAM_QUERY30 {
            get {
                return ResourceManager.GetString("PARAM_QUERY30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C30.
        /// </summary>
        internal static string PARAM_QUERY31 {
            get {
                return ResourceManager.GetString("PARAM_QUERY31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C3.
        /// </summary>
        internal static string PARAM_QUERY4 {
            get {
                return ResourceManager.GetString("PARAM_QUERY4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C4.
        /// </summary>
        internal static string PARAM_QUERY5 {
            get {
                return ResourceManager.GetString("PARAM_QUERY5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C5.
        /// </summary>
        internal static string PARAM_QUERY6 {
            get {
                return ResourceManager.GetString("PARAM_QUERY6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C6.
        /// </summary>
        internal static string PARAM_QUERY7 {
            get {
                return ResourceManager.GetString("PARAM_QUERY7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C7.
        /// </summary>
        internal static string PARAM_QUERY8 {
            get {
                return ResourceManager.GetString("PARAM_QUERY8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C8.
        /// </summary>
        internal static string PARAM_QUERY9 {
            get {
                return ResourceManager.GetString("PARAM_QUERY9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetValuesXMLQuealityControls.
        /// </summary>
        internal static string SP_GetValuesXMLQualityControls {
            get {
                return ResourceManager.GetString("SP_GetValuesXMLQualityControls", resourceCulture);
            }
        }
    }
}
