//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CatValuesCorporativeQualityControlsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatValuesCorporativeQualityControlsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.CatValuesCorporativeQualityControlsResources", typeof(CatValuesCorporativeQualityControlsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1.
        /// </summary>
        internal static string PARAM_C1 {
            get {
                return ResourceManager.GetString("PARAM_C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C10.
        /// </summary>
        internal static string PARAM_C10 {
            get {
                return ResourceManager.GetString("PARAM_C10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C100.
        /// </summary>
        internal static string PARAM_C100 {
            get {
                return ResourceManager.GetString("PARAM_C100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C11.
        /// </summary>
        internal static string PARAM_C11 {
            get {
                return ResourceManager.GetString("PARAM_C11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C12.
        /// </summary>
        internal static string PARAM_C12 {
            get {
                return ResourceManager.GetString("PARAM_C12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C13.
        /// </summary>
        internal static string PARAM_C13 {
            get {
                return ResourceManager.GetString("PARAM_C13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C14.
        /// </summary>
        internal static string PARAM_C14 {
            get {
                return ResourceManager.GetString("PARAM_C14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C15.
        /// </summary>
        internal static string PARAM_C15 {
            get {
                return ResourceManager.GetString("PARAM_C15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C16.
        /// </summary>
        internal static string PARAM_C16 {
            get {
                return ResourceManager.GetString("PARAM_C16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C17.
        /// </summary>
        internal static string PARAM_C17 {
            get {
                return ResourceManager.GetString("PARAM_C17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C18.
        /// </summary>
        internal static string PARAM_C18 {
            get {
                return ResourceManager.GetString("PARAM_C18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C19.
        /// </summary>
        internal static string PARAM_C19 {
            get {
                return ResourceManager.GetString("PARAM_C19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2.
        /// </summary>
        internal static string PARAM_C2 {
            get {
                return ResourceManager.GetString("PARAM_C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C20.
        /// </summary>
        internal static string PARAM_C20 {
            get {
                return ResourceManager.GetString("PARAM_C20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C21.
        /// </summary>
        internal static string PARAM_C21 {
            get {
                return ResourceManager.GetString("PARAM_C21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C22.
        /// </summary>
        internal static string PARAM_C22 {
            get {
                return ResourceManager.GetString("PARAM_C22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C23.
        /// </summary>
        internal static string PARAM_C23 {
            get {
                return ResourceManager.GetString("PARAM_C23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C24.
        /// </summary>
        internal static string PARAM_C24 {
            get {
                return ResourceManager.GetString("PARAM_C24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C25.
        /// </summary>
        internal static string PARAM_C25 {
            get {
                return ResourceManager.GetString("PARAM_C25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C26.
        /// </summary>
        internal static string PARAM_C26 {
            get {
                return ResourceManager.GetString("PARAM_C26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C27.
        /// </summary>
        internal static string PARAM_C27 {
            get {
                return ResourceManager.GetString("PARAM_C27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C28.
        /// </summary>
        internal static string PARAM_C28 {
            get {
                return ResourceManager.GetString("PARAM_C28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C29.
        /// </summary>
        internal static string PARAM_C29 {
            get {
                return ResourceManager.GetString("PARAM_C29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C3.
        /// </summary>
        internal static string PARAM_C3 {
            get {
                return ResourceManager.GetString("PARAM_C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C30.
        /// </summary>
        internal static string PARAM_C30 {
            get {
                return ResourceManager.GetString("PARAM_C30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C31.
        /// </summary>
        internal static string PARAM_C31 {
            get {
                return ResourceManager.GetString("PARAM_C31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C32.
        /// </summary>
        internal static string PARAM_C32 {
            get {
                return ResourceManager.GetString("PARAM_C32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C33.
        /// </summary>
        internal static string PARAM_C33 {
            get {
                return ResourceManager.GetString("PARAM_C33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C34.
        /// </summary>
        internal static string PARAM_C34 {
            get {
                return ResourceManager.GetString("PARAM_C34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C35.
        /// </summary>
        internal static string PARAM_C35 {
            get {
                return ResourceManager.GetString("PARAM_C35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C36.
        /// </summary>
        internal static string PARAM_C36 {
            get {
                return ResourceManager.GetString("PARAM_C36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C37.
        /// </summary>
        internal static string PARAM_C37 {
            get {
                return ResourceManager.GetString("PARAM_C37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C38.
        /// </summary>
        internal static string PARAM_C38 {
            get {
                return ResourceManager.GetString("PARAM_C38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C39.
        /// </summary>
        internal static string PARAM_C39 {
            get {
                return ResourceManager.GetString("PARAM_C39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C4.
        /// </summary>
        internal static string PARAM_C4 {
            get {
                return ResourceManager.GetString("PARAM_C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C40.
        /// </summary>
        internal static string PARAM_C40 {
            get {
                return ResourceManager.GetString("PARAM_C40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C41.
        /// </summary>
        internal static string PARAM_C41 {
            get {
                return ResourceManager.GetString("PARAM_C41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C42.
        /// </summary>
        internal static string PARAM_C42 {
            get {
                return ResourceManager.GetString("PARAM_C42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C43.
        /// </summary>
        internal static string PARAM_C43 {
            get {
                return ResourceManager.GetString("PARAM_C43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C44.
        /// </summary>
        internal static string PARAM_C44 {
            get {
                return ResourceManager.GetString("PARAM_C44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C45.
        /// </summary>
        internal static string PARAM_C45 {
            get {
                return ResourceManager.GetString("PARAM_C45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C46.
        /// </summary>
        internal static string PARAM_C46 {
            get {
                return ResourceManager.GetString("PARAM_C46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C47.
        /// </summary>
        internal static string PARAM_C47 {
            get {
                return ResourceManager.GetString("PARAM_C47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C48.
        /// </summary>
        internal static string PARAM_C48 {
            get {
                return ResourceManager.GetString("PARAM_C48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C49.
        /// </summary>
        internal static string PARAM_C49 {
            get {
                return ResourceManager.GetString("PARAM_C49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C5.
        /// </summary>
        internal static string PARAM_C5 {
            get {
                return ResourceManager.GetString("PARAM_C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C50.
        /// </summary>
        internal static string PARAM_C50 {
            get {
                return ResourceManager.GetString("PARAM_C50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C51.
        /// </summary>
        internal static string PARAM_C51 {
            get {
                return ResourceManager.GetString("PARAM_C51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C52.
        /// </summary>
        internal static string PARAM_C52 {
            get {
                return ResourceManager.GetString("PARAM_C52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C53.
        /// </summary>
        internal static string PARAM_C53 {
            get {
                return ResourceManager.GetString("PARAM_C53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C54.
        /// </summary>
        internal static string PARAM_C54 {
            get {
                return ResourceManager.GetString("PARAM_C54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C55.
        /// </summary>
        internal static string PARAM_C55 {
            get {
                return ResourceManager.GetString("PARAM_C55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C56.
        /// </summary>
        internal static string PARAM_C56 {
            get {
                return ResourceManager.GetString("PARAM_C56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C57.
        /// </summary>
        internal static string PARAM_C57 {
            get {
                return ResourceManager.GetString("PARAM_C57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C58.
        /// </summary>
        internal static string PARAM_C58 {
            get {
                return ResourceManager.GetString("PARAM_C58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C59.
        /// </summary>
        internal static string PARAM_C59 {
            get {
                return ResourceManager.GetString("PARAM_C59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C6.
        /// </summary>
        internal static string PARAM_C6 {
            get {
                return ResourceManager.GetString("PARAM_C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C60.
        /// </summary>
        internal static string PARAM_C60 {
            get {
                return ResourceManager.GetString("PARAM_C60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C61.
        /// </summary>
        internal static string PARAM_C61 {
            get {
                return ResourceManager.GetString("PARAM_C61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C62.
        /// </summary>
        internal static string PARAM_C62 {
            get {
                return ResourceManager.GetString("PARAM_C62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C63.
        /// </summary>
        internal static string PARAM_C63 {
            get {
                return ResourceManager.GetString("PARAM_C63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C64.
        /// </summary>
        internal static string PARAM_C64 {
            get {
                return ResourceManager.GetString("PARAM_C64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C65.
        /// </summary>
        internal static string PARAM_C65 {
            get {
                return ResourceManager.GetString("PARAM_C65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C66.
        /// </summary>
        internal static string PARAM_C66 {
            get {
                return ResourceManager.GetString("PARAM_C66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C67.
        /// </summary>
        internal static string PARAM_C67 {
            get {
                return ResourceManager.GetString("PARAM_C67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C68.
        /// </summary>
        internal static string PARAM_C68 {
            get {
                return ResourceManager.GetString("PARAM_C68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C69.
        /// </summary>
        internal static string PARAM_C69 {
            get {
                return ResourceManager.GetString("PARAM_C69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C7.
        /// </summary>
        internal static string PARAM_C7 {
            get {
                return ResourceManager.GetString("PARAM_C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C70.
        /// </summary>
        internal static string PARAM_C70 {
            get {
                return ResourceManager.GetString("PARAM_C70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C71.
        /// </summary>
        internal static string PARAM_C71 {
            get {
                return ResourceManager.GetString("PARAM_C71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C72.
        /// </summary>
        internal static string PARAM_C72 {
            get {
                return ResourceManager.GetString("PARAM_C72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C73.
        /// </summary>
        internal static string PARAM_C73 {
            get {
                return ResourceManager.GetString("PARAM_C73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C74.
        /// </summary>
        internal static string PARAM_C74 {
            get {
                return ResourceManager.GetString("PARAM_C74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C75.
        /// </summary>
        internal static string PARAM_C75 {
            get {
                return ResourceManager.GetString("PARAM_C75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C76.
        /// </summary>
        internal static string PARAM_C76 {
            get {
                return ResourceManager.GetString("PARAM_C76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C77.
        /// </summary>
        internal static string PARAM_C77 {
            get {
                return ResourceManager.GetString("PARAM_C77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C78.
        /// </summary>
        internal static string PARAM_C78 {
            get {
                return ResourceManager.GetString("PARAM_C78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C79.
        /// </summary>
        internal static string PARAM_C79 {
            get {
                return ResourceManager.GetString("PARAM_C79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C8.
        /// </summary>
        internal static string PARAM_C8 {
            get {
                return ResourceManager.GetString("PARAM_C8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C80.
        /// </summary>
        internal static string PARAM_C80 {
            get {
                return ResourceManager.GetString("PARAM_C80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C81.
        /// </summary>
        internal static string PARAM_C81 {
            get {
                return ResourceManager.GetString("PARAM_C81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C82.
        /// </summary>
        internal static string PARAM_C82 {
            get {
                return ResourceManager.GetString("PARAM_C82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C83.
        /// </summary>
        internal static string PARAM_C83 {
            get {
                return ResourceManager.GetString("PARAM_C83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C84.
        /// </summary>
        internal static string PARAM_C84 {
            get {
                return ResourceManager.GetString("PARAM_C84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C85.
        /// </summary>
        internal static string PARAM_C85 {
            get {
                return ResourceManager.GetString("PARAM_C85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C86.
        /// </summary>
        internal static string PARAM_C86 {
            get {
                return ResourceManager.GetString("PARAM_C86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C87.
        /// </summary>
        internal static string PARAM_C87 {
            get {
                return ResourceManager.GetString("PARAM_C87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C88.
        /// </summary>
        internal static string PARAM_C88 {
            get {
                return ResourceManager.GetString("PARAM_C88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C89.
        /// </summary>
        internal static string PARAM_C89 {
            get {
                return ResourceManager.GetString("PARAM_C89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C9.
        /// </summary>
        internal static string PARAM_C9 {
            get {
                return ResourceManager.GetString("PARAM_C9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C90.
        /// </summary>
        internal static string PARAM_C90 {
            get {
                return ResourceManager.GetString("PARAM_C90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C91.
        /// </summary>
        internal static string PARAM_C91 {
            get {
                return ResourceManager.GetString("PARAM_C91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C92.
        /// </summary>
        internal static string PARAM_C92 {
            get {
                return ResourceManager.GetString("PARAM_C92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C93.
        /// </summary>
        internal static string PARAM_C93 {
            get {
                return ResourceManager.GetString("PARAM_C93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C94.
        /// </summary>
        internal static string PARAM_C94 {
            get {
                return ResourceManager.GetString("PARAM_C94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C95.
        /// </summary>
        internal static string PARAM_C95 {
            get {
                return ResourceManager.GetString("PARAM_C95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C96.
        /// </summary>
        internal static string PARAM_C96 {
            get {
                return ResourceManager.GetString("PARAM_C96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C97.
        /// </summary>
        internal static string PARAM_C97 {
            get {
                return ResourceManager.GetString("PARAM_C97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C98.
        /// </summary>
        internal static string PARAM_C98 {
            get {
                return ResourceManager.GetString("PARAM_C98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C99.
        /// </summary>
        internal static string PARAM_C99 {
            get {
                return ResourceManager.GetString("PARAM_C99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DKToSearch.
        /// </summary>
        internal static string PARAM_QUERY {
            get {
                return ResourceManager.GetString("PARAM_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm.
        /// </summary>
        internal static string PARAM_QUERY2 {
            get {
                return ResourceManager.GetString("PARAM_QUERY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCC.
        /// </summary>
        internal static string PARAM_QUERY3 {
            get {
                return ResourceManager.GetString("PARAM_QUERY3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetValuesQualityControls-100.
        /// </summary>
        internal static string SP_GetValuesQualityControls {
            get {
                return ResourceManager.GetString("SP_GetValuesQualityControls", resourceCulture);
            }
        }
    }
}
