//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsultingFirmResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsultingFirmResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.ConsultingFirmResources", typeof(ConsultingFirmResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        internal static string PARAM_AGENT {
            get {
                return ResourceManager.GetString("PARAM_AGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgentMail.
        /// </summary>
        internal static string PARAM_AGENTMAIL {
            get {
                return ResourceManager.GetString("PARAM_AGENTMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FamilyName.
        /// </summary>
        internal static string PARAM_FAMILYNAME {
            get {
                return ResourceManager.GetString("PARAM_FAMILYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm.
        /// </summary>
        internal static string PARAM_FIRM {
            get {
                return ResourceManager.GetString("PARAM_FIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsMySabreBlocked.
        /// </summary>
        internal static string PARAM_ISMYSABREBLOCKED {
            get {
                return ResourceManager.GetString("PARAM_ISMYSABREBLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyCTSVersion.
        /// </summary>
        internal static string PARAM_MYCTSVERSION {
            get {
                return ResourceManager.GetString("PARAM_MYCTSVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PARAM_PASSWORD {
            get {
                return ResourceManager.GetString("PARAM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCC.
        /// </summary>
        internal static string PARAM_PCC {
            get {
                return ResourceManager.GetString("PARAM_PCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirmtoSearch.
        /// </summary>
        internal static string PARAM_QUERY {
            get {
                return ResourceManager.GetString("PARAM_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCC.
        /// </summary>
        internal static string PARAM_QUERY1 {
            get {
                return ResourceManager.GetString("PARAM_QUERY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        internal static string PARAM_QUEUE {
            get {
                return ResourceManager.GetString("PARAM_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusFirm.
        /// </summary>
        internal static string PARAM_STATUSFIRM {
            get {
                return ResourceManager.GetString("PARAM_STATUSFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TA.
        /// </summary>
        internal static string PARAM_TA {
            get {
                return ResourceManager.GetString("PARAM_TA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserMail.
        /// </summary>
        internal static string PARAM_USERMAIL {
            get {
                return ResourceManager.GetString("PARAM_USERMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string PARAM_USERNAME {
            get {
                return ResourceManager.GetString("PARAM_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetConsultingFirm.
        /// </summary>
        internal static string SP_GetConsultingFirm {
            get {
                return ResourceManager.GetString("SP_GetConsultingFirm", resourceCulture);
            }
        }
    }
}
