//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GetCorporativeFeesRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetCorporativeFeesRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.GetCorporativeFeesRules", typeof(GetCorporativeFeesRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivationState.
        /// </summary>
        internal static string PARAM_ACTIVATIONSTATE {
            get {
                return ResourceManager.GetString("PARAM_ACTIVATIONSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseFare.
        /// </summary>
        internal static string PARAM_BASEFARE {
            get {
                return ResourceManager.GetString("PARAM_BASEFARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Calculada.
        /// </summary>
        internal static string PARAM_CANTIDAD_CALCULADA {
            get {
                return ResourceManager.GetString("PARAM_CANTIDAD_CALCULADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpirationDate.
        /// </summary>
        internal static string PARAM_EXPIRATIONDATE {
            get {
                return ResourceManager.GetString("PARAM_EXPIRATIONDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtendedDescription.
        /// </summary>
        internal static string PARAM_EXTENDEDDESCRIPTION {
            get {
                return ResourceManager.GetString("PARAM_EXTENDEDDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        internal static string PARAM_MANDATORY {
            get {
                return ResourceManager.GetString("PARAM_MANDATORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string PARAM_PRIORITY {
            get {
                return ResourceManager.GetString("PARAM_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location_DKToSearch.
        /// </summary>
        internal static string PARAM_QUERY_DK {
            get {
                return ResourceManager.GetString("PARAM_QUERY_DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string PARAM_QUERY_QUANTITY {
            get {
                return ResourceManager.GetString("PARAM_QUERY_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE1.
        /// </summary>
        internal static string PARAM_QUERY1 {
            get {
                return ResourceManager.GetString("PARAM_QUERY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE10.
        /// </summary>
        internal static string PARAM_QUERY10 {
            get {
                return ResourceManager.GetString("PARAM_QUERY10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE11.
        /// </summary>
        internal static string PARAM_QUERY11 {
            get {
                return ResourceManager.GetString("PARAM_QUERY11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE12.
        /// </summary>
        internal static string PARAM_QUERY12 {
            get {
                return ResourceManager.GetString("PARAM_QUERY12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE13.
        /// </summary>
        internal static string PARAM_QUERY13 {
            get {
                return ResourceManager.GetString("PARAM_QUERY13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE14.
        /// </summary>
        internal static string PARAM_QUERY14 {
            get {
                return ResourceManager.GetString("PARAM_QUERY14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE15.
        /// </summary>
        internal static string PARAM_QUERY15 {
            get {
                return ResourceManager.GetString("PARAM_QUERY15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE16.
        /// </summary>
        internal static string PARAM_QUERY16 {
            get {
                return ResourceManager.GetString("PARAM_QUERY16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE17.
        /// </summary>
        internal static string PARAM_QUERY17 {
            get {
                return ResourceManager.GetString("PARAM_QUERY17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE18.
        /// </summary>
        internal static string PARAM_QUERY18 {
            get {
                return ResourceManager.GetString("PARAM_QUERY18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE19.
        /// </summary>
        internal static string PARAM_QUERY19 {
            get {
                return ResourceManager.GetString("PARAM_QUERY19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE2.
        /// </summary>
        internal static string PARAM_QUERY2 {
            get {
                return ResourceManager.GetString("PARAM_QUERY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE20.
        /// </summary>
        internal static string PARAM_QUERY20 {
            get {
                return ResourceManager.GetString("PARAM_QUERY20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE21.
        /// </summary>
        internal static string PARAM_QUERY21 {
            get {
                return ResourceManager.GetString("PARAM_QUERY21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE23.
        /// </summary>
        internal static string PARAM_QUERY23 {
            get {
                return ResourceManager.GetString("PARAM_QUERY23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE3.
        /// </summary>
        internal static string PARAM_QUERY3 {
            get {
                return ResourceManager.GetString("PARAM_QUERY3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE4.
        /// </summary>
        internal static string PARAM_QUERY4 {
            get {
                return ResourceManager.GetString("PARAM_QUERY4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE5.
        /// </summary>
        internal static string PARAM_QUERY5 {
            get {
                return ResourceManager.GetString("PARAM_QUERY5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE6.
        /// </summary>
        internal static string PARAM_QUERY6 {
            get {
                return ResourceManager.GetString("PARAM_QUERY6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE7.
        /// </summary>
        internal static string PARAM_QUERY7 {
            get {
                return ResourceManager.GetString("PARAM_QUERY7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE8.
        /// </summary>
        internal static string PARAM_QUERY8 {
            get {
                return ResourceManager.GetString("PARAM_QUERY8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TE9.
        /// </summary>
        internal static string PARAM_QUERY9 {
            get {
                return ResourceManager.GetString("PARAM_QUERY9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute1.
        /// </summary>
        internal static string PARAM_QUERYATTRIBUTE1 {
            get {
                return ResourceManager.GetString("PARAM_QUERYATTRIBUTE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleNumber.
        /// </summary>
        internal static string PARAM_RULENUMBER {
            get {
                return ResourceManager.GetString("PARAM_RULENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        internal static string PARAM_STARTDATE {
            get {
                return ResourceManager.GetString("PARAM_STARTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeRange.
        /// </summary>
        internal static string PARAM_TIMERANGE {
            get {
                return ResourceManager.GetString("PARAM_TIMERANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCorporativeFeesRules.
        /// </summary>
        internal static string SP_GetCorporativeFeesRules {
            get {
                return ResourceManager.GetString("SP_GetCorporativeFeesRules", resourceCulture);
            }
        }
    }
}
