//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GetLinkByTkt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetLinkByTkt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.GetLinkByTkt", typeof(GetLinkByTkt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        internal static string PARAM_AGENT {
            get {
                return ResourceManager.GetString("PARAM_AGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescriptionType.
        /// </summary>
        internal static string PARAM_DESCRIPTIONTYPE {
            get {
                return ResourceManager.GetString("PARAM_DESCRIPTIONTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkInvoice.
        /// </summary>
        internal static string PARAM_LINKINVOICE {
            get {
                return ResourceManager.GetString("PARAM_LINKINVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkPassengerReceipt.
        /// </summary>
        internal static string PARAM_LINKPASSENGERRECEIPT {
            get {
                return ResourceManager.GetString("PARAM_LINKPASSENGERRECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkTicketPrinter.
        /// </summary>
        internal static string PARAM_LINKTICKETPRINTER {
            get {
                return ResourceManager.GetString("PARAM_LINKTICKETPRINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkVirtuallyThere.
        /// </summary>
        internal static string PARAM_LINKVIRTUALLYTHERE {
            get {
                return ResourceManager.GetString("PARAM_LINKVIRTUALLYTHERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrgId.
        /// </summary>
        internal static string PARAM_ORG_ID {
            get {
                return ResourceManager.GetString("PARAM_ORG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string PARAM_QUERY1 {
            get {
                return ResourceManager.GetString("PARAM_QUERY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTktLinks.
        /// </summary>
        internal static string SP_GETTKTLINKS {
            get {
                return ResourceManager.GetString("SP_GETTKTLINKS", resourceCulture);
            }
        }
    }
}
