//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelXMLRemarksResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelXMLRemarksResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.LabelXMLRemarksResources", typeof(LabelXMLRemarksResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute1.
        /// </summary>
        internal static string PARAM_QUERY1 {
            get {
                return ResourceManager.GetString("PARAM_QUERY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDProcess.
        /// </summary>
        internal static string PARAM_QUERY2 {
            get {
                return ResourceManager.GetString("PARAM_QUERY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketPosition.
        /// </summary>
        internal static string PARAM_QUERY3 {
            get {
                return ResourceManager.GetString("PARAM_QUERY3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemarkValue.
        /// </summary>
        internal static string PARAM_QUERY4 {
            get {
                return ResourceManager.GetString("PARAM_QUERY4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMLActualLabel.
        /// </summary>
        internal static string PARAM_XMLACTUALLABEL {
            get {
                return ResourceManager.GetString("PARAM_XMLACTUALLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMLFutureLabel.
        /// </summary>
        internal static string PARAM_XMLFUTURELABEL {
            get {
                return ResourceManager.GetString("PARAM_XMLFUTURELABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLabelXMLRemarks.
        /// </summary>
        internal static string SP_GetLabelXMLRemarks {
            get {
                return ResourceManager.GetString("SP_GetLabelXMLRemarks", resourceCulture);
            }
        }
    }
}
