//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4961
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogNewFormatProfilesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogNewFormatProfilesResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.LogNewFormatProfilesResources", typeof(LogNewFormatProfilesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ModifiedDate.
        /// </summary>
        internal static string PARAM_GET_MODIFIED_DATE {
            get {
                return ResourceManager.GetString("PARAM_GET_MODIFIED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UserName.
        /// </summary>
        internal static string PARAM_GET_USER_NAME {
            get {
                return ResourceManager.GetString("PARAM_GET_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @level.
        /// </summary>
        internal static string PARAM_LEVEL {
            get {
                return ResourceManager.GetString("PARAM_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @date.
        /// </summary>
        internal static string PARAM_MODIFIED_DATE {
            get {
                return ResourceManager.GetString("PARAM_MODIFIED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Pccid.
        /// </summary>
        internal static string PARAM_PCC {
            get {
                return ResourceManager.GetString("PARAM_PCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Star1Name.
        /// </summary>
        internal static string PARAM_STARLEVEL1 {
            get {
                return ResourceManager.GetString("PARAM_STARLEVEL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Star2Name.
        /// </summary>
        internal static string PARAM_STARLEVEL2 {
            get {
                return ResourceManager.GetString("PARAM_STARLEVEL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @userName.
        /// </summary>
        internal static string PARAM_USER_NAME {
            get {
                return ResourceManager.GetString("PARAM_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetLogNewFormatProfiles.
        /// </summary>
        internal static string SP_GetLogNewFormatProfiles {
            get {
                return ResourceManager.GetString("SP_GetLogNewFormatProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SetLogNewFormatProfiles.
        /// </summary>
        internal static string SP_SetLogNewFormatProfiles {
            get {
                return ResourceManager.GetString("SP_SetLogNewFormatProfiles", resourceCulture);
            }
        }
    }
}
