//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogNotOnlinePayServices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogNotOnlinePayServices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.LogNotOnlinePayServices", typeof(LogNotOnlinePayServices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fcAutorization.
        /// </summary>
        internal static string PARAM_fcAutorization {
            get {
                return ResourceManager.GetString("PARAM_fcAutorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fcBoleto.
        /// </summary>
        internal static string PARAM_fcBoleto {
            get {
                return ResourceManager.GetString("PARAM_fcBoleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fcFormTypeCodeFOP.
        /// </summary>
        internal static string PARAM_fcFormTypeCodeFOP {
            get {
                return ResourceManager.GetString("PARAM_fcFormTypeCodeFOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fcOperation.
        /// </summary>
        internal static string PARAM_fcOperation {
            get {
                return ResourceManager.GetString("PARAM_fcOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fcPNR.
        /// </summary>
        internal static string PARAM_fcPNR {
            get {
                return ResourceManager.GetString("PARAM_fcPNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fcRemark.
        /// </summary>
        internal static string PARAM_fcRemark {
            get {
                return ResourceManager.GetString("PARAM_fcRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fcTarjeta.
        /// </summary>
        internal static string PARAM_fcTarjeta {
            get {
                return ResourceManager.GetString("PARAM_fcTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fdFolioInterno.
        /// </summary>
        internal static string PARAM_fdFolioInterno {
            get {
                return ResourceManager.GetString("PARAM_fdFolioInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fdMonto.
        /// </summary>
        internal static string PARAM_fdMonto {
            get {
                return ResourceManager.GetString("PARAM_fdMonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fiPaxNumber.
        /// </summary>
        internal static string PARAM_fiPaxNumber {
            get {
                return ResourceManager.GetString("PARAM_fiPaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spInsertNotOnlinePayServices.
        /// </summary>
        internal static string SP_InsertNotOnlinePayServices {
            get {
                return ResourceManager.GetString("SP_InsertNotOnlinePayServices", resourceCulture);
            }
        }
    }
}
