//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SabreMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SabreMessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.SabreMessageResources", typeof(SabreMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIMessage.
        /// </summary>
        internal static string PARAM_APIMESSAGE {
            get {
                return ResourceManager.GetString("PARAM_APIMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string PARAM_ID {
            get {
                return ResourceManager.GetString("PARAM_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncludeConditionals.
        /// </summary>
        internal static string PARAM_INCLUDECONDITIONALS {
            get {
                return ResourceManager.GetString("PARAM_INCLUDECONDITIONALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsConditional.
        /// </summary>
        internal static string PARAM_ISCONDITIONAL {
            get {
                return ResourceManager.GetString("PARAM_ISCONDITIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModuleID.
        /// </summary>
        internal static string PARAM_MODULEID {
            get {
                return ResourceManager.GetString("PARAM_MODULEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowControl.
        /// </summary>
        internal static string PARAM_SHOWCONTROL {
            get {
                return ResourceManager.GetString("PARAM_SHOWCONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserMessage.
        /// </summary>
        internal static string PARAM_USERMESSAGE {
            get {
                return ResourceManager.GetString("PARAM_USERMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSabreMessages.
        /// </summary>
        internal static string SP_GetSabreMessages {
            get {
                return ResourceManager.GetString("SP_GetSabreMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSingleSabreMessage.
        /// </summary>
        internal static string SP_GetSingleSabreMessage {
            get {
                return ResourceManager.GetString("SP_GetSingleSabreMessage", resourceCulture);
            }
        }
    }
}
