//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SetAllFirmModulesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SetAllFirmModulesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.SetAllFirmModulesResources", typeof(SetAllFirmModulesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iata.
        /// </summary>
        internal static string PARAM_IATA {
            get {
                return ResourceManager.GetString("PARAM_IATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string PARAM_OFFICE {
            get {
                return ResourceManager.GetString("PARAM_OFFICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcc.
        /// </summary>
        internal static string PARAM_PCC {
            get {
                return ResourceManager.GetString("PARAM_PCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TA.
        /// </summary>
        internal static string PARAM_TA {
            get {
                return ResourceManager.GetString("PARAM_TA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string PARAM_TYPE {
            get {
                return ResourceManager.GetString("PARAM_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertIATA.
        /// </summary>
        internal static string SP_InsertIATA {
            get {
                return ResourceManager.GetString("SP_InsertIATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertTA.
        /// </summary>
        internal static string SP_InsertTA {
            get {
                return ResourceManager.GetString("SP_InsertTA", resourceCulture);
            }
        }
    }
}
