//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SetStar1Details {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SetStar1Details() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.SetStar1Details", typeof(SetStar1Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string PARAM_City {
            get {
                return ResourceManager.GetString("PARAM_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colony.
        /// </summary>
        internal static string PARAM_Colony {
            get {
                return ResourceManager.GetString("PARAM_Colony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string PARAM_Comments {
            get {
                return ResourceManager.GetString("PARAM_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyName.
        /// </summary>
        internal static string PARAM_CompanyName {
            get {
                return ResourceManager.GetString("PARAM_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactCompany.
        /// </summary>
        internal static string PARAM_ContactCompany {
            get {
                return ResourceManager.GetString("PARAM_ContactCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedBy.
        /// </summary>
        internal static string PARAM_CreatedBy {
            get {
                return ResourceManager.GetString("PARAM_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditCard.
        /// </summary>
        internal static string PARAM_CreditCard {
            get {
                return ResourceManager.GetString("PARAM_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerDK.
        /// </summary>
        internal static string PARAM_CustomerDK {
            get {
                return ResourceManager.GetString("PARAM_CustomerDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string PARAM_Email {
            get {
                return ResourceManager.GetString("PARAM_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpirationDate.
        /// </summary>
        internal static string PARAM_ExpiratioDate {
            get {
                return ResourceManager.GetString("PARAM_ExpiratioDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext.
        /// </summary>
        internal static string PARAM_Ext {
            get {
                return ResourceManager.GetString("PARAM_Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraData.
        /// </summary>
        internal static string PARAM_ExtraData {
            get {
                return ResourceManager.GetString("PARAM_ExtraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idStar1SF.
        /// </summary>
        internal static string PARAM_idStar1SF {
            get {
                return ResourceManager.GetString("PARAM_idStar1SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalNumber.
        /// </summary>
        internal static string PARAM_InternalNumber {
            get {
                return ResourceManager.GetString("PARAM_InternalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        internal static string PARAM_Municipality {
            get {
                return ResourceManager.GetString("PARAM_Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutsideNumber.
        /// </summary>
        internal static string PARAM_OutsideNumber {
            get {
                return ResourceManager.GetString("PARAM_OutsideNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PARAM_Password {
            get {
                return ResourceManager.GetString("PARAM_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCC.
        /// </summary>
        internal static string PARAM_PCC {
            get {
                return ResourceManager.GetString("PARAM_PCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalCode.
        /// </summary>
        internal static string PARAM_PostalCode {
            get {
                return ResourceManager.GetString("PARAM_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileName.
        /// </summary>
        internal static string PARAM_ProfileName {
            get {
                return ResourceManager.GetString("PARAM_ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC.
        /// </summary>
        internal static string PARAM_RFC {
            get {
                return ResourceManager.GetString("PARAM_RFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocialReason.
        /// </summary>
        internal static string PARAM_SocialReason {
            get {
                return ResourceManager.GetString("PARAM_SocialReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string PARAM_State {
            get {
                return ResourceManager.GetString("PARAM_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string PARAM_Street {
            get {
                return ResourceManager.GetString("PARAM_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string PARAM_Telephone {
            get {
                return ResourceManager.GetString("PARAM_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TravelPolicies.
        /// </summary>
        internal static string PARAM_TravelPolicies {
            get {
                return ResourceManager.GetString("PARAM_TravelPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetStar1Details.
        /// </summary>
        internal static string SP_SetStar1Details {
            get {
                return ResourceManager.GetString("SP_SetStar1Details", resourceCulture);
            }
        }
    }
}
