//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatusFamilyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusFamilyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.StatusFamilyResources", typeof(StatusFamilyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FamilyName.
        /// </summary>
        internal static string PARAM_FAMILYNAME {
            get {
                return ResourceManager.GetString("PARAM_FAMILYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCC.
        /// </summary>
        internal static string PARAM_PCC {
            get {
                return ResourceManager.GetString("PARAM_PCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Firm.
        /// </summary>
        internal static string PARAM_QUERY {
            get {
                return ResourceManager.GetString("PARAM_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PCC.
        /// </summary>
        internal static string PARAM_QUERY2 {
            get {
                return ResourceManager.GetString("PARAM_QUERY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusFirm.
        /// </summary>
        internal static string PARAM_STATUSFIRM {
            get {
                return ResourceManager.GetString("PARAM_STATUSFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_StatusFamilyName.
        /// </summary>
        internal static string SP_GETSTATUSFAMILYNAME {
            get {
                return ResourceManager.GetString("SP_GETSTATUSFAMILYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get_StatusFamilyName2.
        /// </summary>
        internal static string SP_GETSTATUSFAMILYNAME2 {
            get {
                return ResourceManager.GetString("SP_GETSTATUSFAMILYNAME2", resourceCulture);
            }
        }
    }
}
