//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateImagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateImagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.UpdateImagesResources", typeof(UpdateImagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Activate.
        /// </summary>
        internal static string PARAM_ACTIVATE {
            get {
                return ResourceManager.GetString("PARAM_ACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Content.
        /// </summary>
        internal static string PARAM_CONTENT {
            get {
                return ResourceManager.GetString("PARAM_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Extension.
        /// </summary>
        internal static string PARAM_EXTENSION {
            get {
                return ResourceManager.GetString("PARAM_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IDAirline.
        /// </summary>
        internal static string PARAM_IDAIRLINE {
            get {
                return ResourceManager.GetString("PARAM_IDAIRLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LogoAirline.
        /// </summary>
        internal static string PARAM_LOGOAIRLINE {
            get {
                return ResourceManager.GetString("PARAM_LOGOAIRLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Name.
        /// </summary>
        internal static string PARAM_NAME {
            get {
                return ResourceManager.GetString("PARAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Url.
        /// </summary>
        internal static string PARAM_URL {
            get {
                return ResourceManager.GetString("PARAM_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBannerImage.
        /// </summary>
        internal static string SP_SETBANNERIMAGE {
            get {
                return ResourceManager.GetString("SP_SETBANNERIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetLogoAirline.
        /// </summary>
        internal static string SP_SETLOGOAIRLINE {
            get {
                return ResourceManager.GetString("SP_SETLOGOAIRLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateBannerImageTicketPrinter.
        /// </summary>
        internal static string SP_UPDATEBANNERIMAGETICKETPRINTER {
            get {
                return ResourceManager.GetString("SP_UPDATEBANNERIMAGETICKETPRINTER", resourceCulture);
            }
        }
    }
}
