//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCTS.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserProductivityGenericResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserProductivityGenericResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCTS.DataAccess.Resources.UserProductivityGenericResources", typeof(UserProductivityGenericResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AirSegment1.
        /// </summary>
        internal static string PARAM_AIRSEGMENT1 {
            get {
                return ResourceManager.GetString("PARAM_AIRSEGMENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AirSegment2.
        /// </summary>
        internal static string PARAM_AIRSEGMENT2 {
            get {
                return ResourceManager.GetString("PARAM_AIRSEGMENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AirSegmentProductivity.
        /// </summary>
        internal static string PARAM_AIRSEGMENTPRODUCTIVITY {
            get {
                return ResourceManager.GetString("PARAM_AIRSEGMENTPRODUCTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AirSegmentProductivity1.
        /// </summary>
        internal static string PARAM_AIRSEGMENTPRODUCTIVITY1 {
            get {
                return ResourceManager.GetString("PARAM_AIRSEGMENTPRODUCTIVITY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AirSegmentProductivity2.
        /// </summary>
        internal static string PARAM_AIRSEGMENTPRODUCTIVITY2 {
            get {
                return ResourceManager.GetString("PARAM_AIRSEGMENTPRODUCTIVITY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSegment1.
        /// </summary>
        internal static string PARAM_AUTOSEGMENT1 {
            get {
                return ResourceManager.GetString("PARAM_AUTOSEGMENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSegment2.
        /// </summary>
        internal static string PARAM_AUTOSEGMENT2 {
            get {
                return ResourceManager.GetString("PARAM_AUTOSEGMENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSegmentProductivity.
        /// </summary>
        internal static string PARAM_AUTOSEGMENTPRODUCTIVITY {
            get {
                return ResourceManager.GetString("PARAM_AUTOSEGMENTPRODUCTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSegmentProductivity1.
        /// </summary>
        internal static string PARAM_AUTOSEGMENTPRODUCTIVITY1 {
            get {
                return ResourceManager.GetString("PARAM_AUTOSEGMENTPRODUCTIVITY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSegmentProductivity2.
        /// </summary>
        internal static string PARAM_AUTOSEGMENTPRODUCTIVITY2 {
            get {
                return ResourceManager.GetString("PARAM_AUTOSEGMENTPRODUCTIVITY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgRecordVsTicket1.
        /// </summary>
        internal static string PARAM_AVBRECORDVSTICKET1 {
            get {
                return ResourceManager.GetString("PARAM_AVBRECORDVSTICKET1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgRecordVsTicket2.
        /// </summary>
        internal static string PARAM_AVBRECORDVSTICKET2 {
            get {
                return ResourceManager.GetString("PARAM_AVBRECORDVSTICKET2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgAirSegment1.
        /// </summary>
        internal static string PARAM_AVGAIRSEGMENT1 {
            get {
                return ResourceManager.GetString("PARAM_AVGAIRSEGMENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgAirSegment2.
        /// </summary>
        internal static string PARAM_AVGAIRSEGMENT2 {
            get {
                return ResourceManager.GetString("PARAM_AVGAIRSEGMENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgAutoSegment1.
        /// </summary>
        internal static string PARAM_AVGAUTOSEGMENT1 {
            get {
                return ResourceManager.GetString("PARAM_AVGAUTOSEGMENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgAutoSegment2.
        /// </summary>
        internal static string PARAM_AVGAUTOSEGMENT2 {
            get {
                return ResourceManager.GetString("PARAM_AVGAUTOSEGMENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgCancelledRecords1.
        /// </summary>
        internal static string PARAM_AVGCANCELLEDRECORDS1 {
            get {
                return ResourceManager.GetString("PARAM_AVGCANCELLEDRECORDS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgCancelledRecords2.
        /// </summary>
        internal static string PARAM_AVGCANCELLEDRECORDS2 {
            get {
                return ResourceManager.GetString("PARAM_AVGCANCELLEDRECORDS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgCancelledTKT1.
        /// </summary>
        internal static string PARAM_AVGCANCELLEDTKT1 {
            get {
                return ResourceManager.GetString("PARAM_AVGCANCELLEDTKT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgCancelledTKT2.
        /// </summary>
        internal static string PARAM_AVGCANCELLEDTKT2 {
            get {
                return ResourceManager.GetString("PARAM_AVGCANCELLEDTKT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgEmittedTKT1.
        /// </summary>
        internal static string PARAM_AVGEMITTEDTKT1 {
            get {
                return ResourceManager.GetString("PARAM_AVGEMITTEDTKT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgEmittedTKT2.
        /// </summary>
        internal static string PARAM_AVGEMITTEDTKT2 {
            get {
                return ResourceManager.GetString("PARAM_AVGEMITTEDTKT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgHotelSegment1.
        /// </summary>
        internal static string PARAM_AVGHOTELSEGMENT1 {
            get {
                return ResourceManager.GetString("PARAM_AVGHOTELSEGMENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgHotelSegment2.
        /// </summary>
        internal static string PARAM_AVGHOTELSEGMENT2 {
            get {
                return ResourceManager.GetString("PARAM_AVGHOTELSEGMENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgRecords1.
        /// </summary>
        internal static string PARAM_AVGRECORDS1 {
            get {
                return ResourceManager.GetString("PARAM_AVGRECORDS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgRecords2.
        /// </summary>
        internal static string PARAM_AVGRECORDS2 {
            get {
                return ResourceManager.GetString("PARAM_AVGRECORDS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgRecordVsTicket1.
        /// </summary>
        internal static string PARAM_AVGRECORDSVSTICKET1 {
            get {
                return ResourceManager.GetString("PARAM_AVGRECORDSVSTICKET1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgRecordVsTicket2.
        /// </summary>
        internal static string PARAM_AVGRECORDSVSTICKET2 {
            get {
                return ResourceManager.GetString("PARAM_AVGRECORDSVSTICKET2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgScanAvgPerRecord1.
        /// </summary>
        internal static string PARAM_AVGSCANAVGPERRECORD1 {
            get {
                return ResourceManager.GetString("PARAM_AVGSCANAVGPERRECORD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgScanAvgPerRecord2.
        /// </summary>
        internal static string PARAM_AVGSCANAVGPERRECORD2 {
            get {
                return ResourceManager.GetString("PARAM_AVGSCANAVGPERRECORD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgScanPerRecordProductivity1.
        /// </summary>
        internal static string PARAM_AVGSCANPERRECORDPRODUCTIVITY1 {
            get {
                return ResourceManager.GetString("PARAM_AVGSCANPERRECORDPRODUCTIVITY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgScanPerRecordProductivity2.
        /// </summary>
        internal static string PARAM_AVGSCANPERRECORDPRODUCTIVITY2 {
            get {
                return ResourceManager.GetString("PARAM_AVGSCANPERRECORDPRODUCTIVITY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgTotalSegment1.
        /// </summary>
        internal static string PARAM_AVGTOTALSEGMENT1 {
            get {
                return ResourceManager.GetString("PARAM_AVGTOTALSEGMENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvgTotalSegment2.
        /// </summary>
        internal static string PARAM_AVGTOTALSEGMENT2 {
            get {
                return ResourceManager.GetString("PARAM_AVGTOTALSEGMENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelledPNR1.
        /// </summary>
        internal static string PARAM_CANCELLEDPNR1 {
            get {
                return ResourceManager.GetString("PARAM_CANCELLEDPNR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelledPNR2.
        /// </summary>
        internal static string PARAM_CANCELLEDPNR2 {
            get {
                return ResourceManager.GetString("PARAM_CANCELLEDPNR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelledRecordsProductivity.
        /// </summary>
        internal static string PARAM_CANCELLEDRECORDSPRODUCTIVITY {
            get {
                return ResourceManager.GetString("PARAM_CANCELLEDRECORDSPRODUCTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelledRecordsProductivity1.
        /// </summary>
        internal static string PARAM_CANCELLEDRECORDSPRODUCTIVITY1 {
            get {
                return ResourceManager.GetString("PARAM_CANCELLEDRECORDSPRODUCTIVITY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelledRecordsProductivity2.
        /// </summary>
        internal static string PARAM_CANCELLEDRECORDSPRODUCTIVITY2 {
            get {
                return ResourceManager.GetString("PARAM_CANCELLEDRECORDSPRODUCTIVITY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelledTKT1.
        /// </summary>
        internal static string PARAM_CANCELLEDTKT1 {
            get {
                return ResourceManager.GetString("PARAM_CANCELLEDTKT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelledTKT2.
        /// </summary>
        internal static string PARAM_CANCELLEDTKT2 {
            get {
                return ResourceManager.GetString("PARAM_CANCELLEDTKT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelledTKTProductivity.
        /// </summary>
        internal static string PARAM_CANCELLEDTKTPRODUCTIVITY {
            get {
                return ResourceManager.GetString("PARAM_CANCELLEDTKTPRODUCTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelledTKTProductivity1.
        /// </summary>
        internal static string PARAM_CANCELLEDTKTPRODUCTIVITY1 {
            get {
                return ResourceManager.GetString("PARAM_CANCELLEDTKTPRODUCTIVITY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelledTKTProductivity2.
        /// </summary>
        internal static string PARAM_CANCELLEDTKTPRODUCTIVITY2 {
            get {
                return ResourceManager.GetString("PARAM_CANCELLEDTKTPRODUCTIVITY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmittedTKT1.
        /// </summary>
        internal static string PARAM_EMITTEDTKT1 {
            get {
                return ResourceManager.GetString("PARAM_EMITTEDTKT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmittedTKT2.
        /// </summary>
        internal static string PARAM_EMITTEDTKT2 {
            get {
                return ResourceManager.GetString("PARAM_EMITTEDTKT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmittedTKTProductivity.
        /// </summary>
        internal static string PARAM_EMITTEDTKTPRODUCTIVITY {
            get {
                return ResourceManager.GetString("PARAM_EMITTEDTKTPRODUCTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmittedTKTProductivity1.
        /// </summary>
        internal static string PARAM_EMITTEDTKTPRODUCTIVITY1 {
            get {
                return ResourceManager.GetString("PARAM_EMITTEDTKTPRODUCTIVITY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmittedTKTProductivity2.
        /// </summary>
        internal static string PARAM_EMITTEDTKTPRODUCTIVITY2 {
            get {
                return ResourceManager.GetString("PARAM_EMITTEDTKTPRODUCTIVITY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FamilyName.
        /// </summary>
        internal static string PARAM_FAMILYNAME {
            get {
                return ResourceManager.GetString("PARAM_FAMILYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinalDate1.
        /// </summary>
        internal static string PARAM_FINALDATE1 {
            get {
                return ResourceManager.GetString("PARAM_FINALDATE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinalDate2.
        /// </summary>
        internal static string PARAM_FINALDATE2 {
            get {
                return ResourceManager.GetString("PARAM_FINALDATE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotelSegment1.
        /// </summary>
        internal static string PARAM_HOTELSEGMENT1 {
            get {
                return ResourceManager.GetString("PARAM_HOTELSEGMENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotelSegment2.
        /// </summary>
        internal static string PARAM_HOTELSEGMENT2 {
            get {
                return ResourceManager.GetString("PARAM_HOTELSEGMENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotelSegmentProductivity.
        /// </summary>
        internal static string PARAM_HOTELSEGMENTPRODUCTIVITY {
            get {
                return ResourceManager.GetString("PARAM_HOTELSEGMENTPRODUCTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotelSegmentProductivity1.
        /// </summary>
        internal static string PARAM_HOTELSEGMENTPRODUCTIVITY1 {
            get {
                return ResourceManager.GetString("PARAM_HOTELSEGMENTPRODUCTIVITY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotelSegmentProductivity2.
        /// </summary>
        internal static string PARAM_HOTELSEGMENTPRODUCTIVITY2 {
            get {
                return ResourceManager.GetString("PARAM_HOTELSEGMENTPRODUCTIVITY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialDate1.
        /// </summary>
        internal static string PARAM_INITIALDATE1 {
            get {
                return ResourceManager.GetString("PARAM_INITIALDATE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialDate2.
        /// </summary>
        internal static string PARAM_INITIALDATE2 {
            get {
                return ResourceManager.GetString("PARAM_INITIALDATE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabourDays1.
        /// </summary>
        internal static string PARAM_LABOURDAYS1 {
            get {
                return ResourceManager.GetString("PARAM_LABOURDAYS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabourDays2.
        /// </summary>
        internal static string PARAM_LABOURDAYS2 {
            get {
                return ResourceManager.GetString("PARAM_LABOURDAYS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        internal static string PARAM_QUERY {
            get {
                return ResourceManager.GetString("PARAM_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductivityDate.
        /// </summary>
        internal static string PARAM_QUERY2 {
            get {
                return ResourceManager.GetString("PARAM_QUERY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordsProductivity1.
        /// </summary>
        internal static string PARAM_RECORDSPRODUCTIVITY1 {
            get {
                return ResourceManager.GetString("PARAM_RECORDSPRODUCTIVITY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordsProductivity2.
        /// </summary>
        internal static string PARAM_RECORDSPRODUCTIVITY2 {
            get {
                return ResourceManager.GetString("PARAM_RECORDSPRODUCTIVITY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordVsTicket1.
        /// </summary>
        internal static string PARAM_RECORDSVSTICKET1 {
            get {
                return ResourceManager.GetString("PARAM_RECORDSVSTICKET1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordVsTicket2.
        /// </summary>
        internal static string PARAM_RECORDSVSTICKET2 {
            get {
                return ResourceManager.GetString("PARAM_RECORDSVSTICKET2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordVsTicketProductivity.
        /// </summary>
        internal static string PARAM_RECORDSVSTKTPRODUCTIVITY {
            get {
                return ResourceManager.GetString("PARAM_RECORDSVSTKTPRODUCTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportDate.
        /// </summary>
        internal static string PARAM_REPORTDATE {
            get {
                return ResourceManager.GetString("PARAM_REPORTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScansAverage1.
        /// </summary>
        internal static string PARAM_SCANSAVERAGE1 {
            get {
                return ResourceManager.GetString("PARAM_SCANSAVERAGE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScansAverage2.
        /// </summary>
        internal static string PARAM_SCANSAVERAGE2 {
            get {
                return ResourceManager.GetString("PARAM_SCANSAVERAGE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScansAverageProductivity.
        /// </summary>
        internal static string PARAM_SCANSAVERAGEPRODUCTIVITY {
            get {
                return ResourceManager.GetString("PARAM_SCANSAVERAGEPRODUCTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalPNR1.
        /// </summary>
        internal static string PARAM_TOTALPNR1 {
            get {
                return ResourceManager.GetString("PARAM_TOTALPNR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalPNR2.
        /// </summary>
        internal static string PARAM_TOTALPNR2 {
            get {
                return ResourceManager.GetString("PARAM_TOTALPNR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalRecordsProductivity.
        /// </summary>
        internal static string PARAM_TOTALRECORDSPRODUCTIVITY {
            get {
                return ResourceManager.GetString("PARAM_TOTALRECORDSPRODUCTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalRecordVsTKTProductivity1.
        /// </summary>
        internal static string PARAM_TOTALRECORDSVSTKTPRODUCTIVITY1 {
            get {
                return ResourceManager.GetString("PARAM_TOTALRECORDSVSTKTPRODUCTIVITY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalRecordVsTKTProductivity2.
        /// </summary>
        internal static string PARAM_TOTALRECORDSVSTKTPRODUCTIVITY2 {
            get {
                return ResourceManager.GetString("PARAM_TOTALRECORDSVSTKTPRODUCTIVITY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalSegment1.
        /// </summary>
        internal static string PARAM_TOTALSEGMENT1 {
            get {
                return ResourceManager.GetString("PARAM_TOTALSEGMENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalSegment2.
        /// </summary>
        internal static string PARAM_TOTALSEGMENT2 {
            get {
                return ResourceManager.GetString("PARAM_TOTALSEGMENT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalSegmentProductivity.
        /// </summary>
        internal static string PARAM_TOTALSEGMENTPRODUCTIVITY {
            get {
                return ResourceManager.GetString("PARAM_TOTALSEGMENTPRODUCTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalSegmentProductivity1.
        /// </summary>
        internal static string PARAM_TOTALSEGMENTPRODUCTIVITY1 {
            get {
                return ResourceManager.GetString("PARAM_TOTALSEGMENTPRODUCTIVITY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalSegmentProductivity2.
        /// </summary>
        internal static string PARAM_TOTALSEGMENTPRODUCTIVITY2 {
            get {
                return ResourceManager.GetString("PARAM_TOTALSEGMENTPRODUCTIVITY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserProductivityAccumulated.
        /// </summary>
        internal static string SP_GetUserProductivityAccumulated {
            get {
                return ResourceManager.GetString("SP_GetUserProductivityAccumulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserProductivityPerMonth.
        /// </summary>
        internal static string SP_GetUserProductivityPerMonth {
            get {
                return ResourceManager.GetString("SP_GetUserProductivityPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserProductivityPerWeek.
        /// </summary>
        internal static string SP_GetUserProductivityPerWeek {
            get {
                return ResourceManager.GetString("SP_GetUserProductivityPerWeek", resourceCulture);
            }
        }
    }
}
